### ISSUE TITLE
Feature - Folder to organize Subscriptions

### ISSUE THREAD

**Issue by wetterSpitze** [hello-efficiency-inc/raven-reader#152]
It would be a very nice feature if there is a way to organize subscriptions under specific topics / folders like [Feedly](https://feedly.com/) is providing it. :wink: 

![auswahl_003](https://user-images.githubusercontent.com/17545206/48092306-97427500-e20c-11e8-8501-7434917ff8e7.png)

**Comment by raulcraveiro** [comment]
That's the only thing that stops me to use Raven Reader. I would love to see this. ♥

**Comment by mrgodhani** [comment]
This would be coming in next release. It won't be folders but would be instead called *Category*

**Comment by raulcraveiro** [comment]
This is amazing! Is there a date for the new release?

**Comment by mrgodhani** [comment]
Depending on how my time goes. But this weekend is my target.

**Comment by raulcraveiro** [comment]
I'll keep an eye on it then. Good luck! ;)

**Comment by mrgodhani** [comment]
https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v0.6.0 added in new release
