### ISSUE TITLE
Integrate fivefilter RSS filters.

### ISSUE THREAD

**Issue by nmabhinandan** [hello-efficiency-inc/raven-reader#168]
Some sources limit the article contents to a few sentences and force us to visit their site to read full article. FilveFilters is a crowd sourced filters which can be used to fetch full articles from their websites. It'd be great if you integrate them within your app.

**Comment by nmabhinandan** [comment]
...

**Comment by mrgodhani** [comment]
@nmabhinandan I will look into this. Please note that is only one developer maintaining this software. IF you have idea to contribute please feel free to open PR

**Comment by nmabhinandan** [comment]
Now that it's a paid app, this would be a cool feature to have!
