### ISSUE TITLE
 [Feature Request] New Article Notification

### ISSUE THREAD

**Issue by zero77** [hello-efficiency-inc/raven-reader#270]
Can you please add notification support for new articles.
Thanks

**Comment by mrgodhani** [comment]
@zero77 There is notification right now. What operating system are you using?

**Comment by zero77** [comment]
I am using ubuntu 18.04 with openbox and i3 but i haven't tested it in i3 yet.

**Comment by zero77** [comment]
@stale
Issue is unresolved.

**Comment by mrgodhani** [comment]
Fixed in v1.0.8
