### ISSUE TITLE
No images in articles

### ISSUE THREAD

**Issue by IevgenSobko** [hello-efficiency-inc/raven-reader#286]
**Describe the bug**
After adding few sources and opening few articles images stopped to apear in articles

**To Reproduce**
1. Add 2 sources
2. Open few articles
3. After some time articles stop to show images

**Expected behavior**
Images displayed 

**Screenshots**
![2019-02-14__21-42-53](https://user-images.githubusercontent.com/14232100/52814148-19f88d00-30a4-11e9-97c8-a4db8658b534.png)
![2019-02-14__21-44-07](https://user-images.githubusercontent.com/14232100/52814150-19f88d00-30a4-11e9-8cc4-efcd1681c445.png)

**Desktop (please complete the following information):**
 - Kernel: 4.20.7-arch1-1
 - ARCH x86_64 bits: 64 
 - Desktop: KDE Plasma 5.15.0 
 - Distro: Antergos Linux
raven-reader-0.4.1-x86_64.AppImage

**Comment by mrgodhani** [comment]
@IevgenSobko By any chance you use proxy or anything?

**Comment by IevgenSobko** [comment]
@mrgodhani No, I don't

**Comment by mrgodhani** [comment]
ok will have a look thanks @IevgenSobko

**Comment by anonymous133** [comment]
I have the same behaviour:

* Kernel: 4.20.12.a-1-hardened
* ARCH x86_64 bits: 64
* Desktop: i3 Window Manager
* Distro: Antergos Linux
* raven-reader-0.4.**3**-x86_64.AppImage

**Comment by DevangLiya** [comment]
I have a similar problem. My reader doesn't show images at all instead of them disappearing after a few articles as described by @IevgenSobko 

My system info:
- Kernel: 4.15.0-46-generic
- ARCH x86_64 bits: 64
- Desktop: GNOME 3.28.2
- Distro: Ubuntu 18.04
- Raven Reader version: 0.4.3
