### ISSUE TITLE
Tiny Tiny RSS aka TTRSS support.

### ISSUE THREAD

**Issue by alkaphreak** [hello-efficiency-inc/raven-reader#300]
Hi, TTRSS (https://tt-rss.org/) is nice a RSS web selfhosted app but for my desktop day to day use i'de like to be able to use your client.

**Comment by JohnGalt1717** [comment]
Would love to see this or fever api support.

**Comment by somedevreally** [comment]
+1 for tt-rss support

**Comment by flappysquirrel** [comment]
Actually, tt-rss is supported. Just not in this repo.

1) download the master (releases are outdated) zip from here: 

https://github.com/DigitalDJ/tinytinyrss-fever-plugin

2) unpack the folder, rename it to `fever`, upload to plugins.local

3) set up the fever plugin in tt-rss

4) download another rss reader to see if your config is working:

https://github.com/yang991178/fluent-reader

5) and finally, download this fork, and set up your C:\Users\[USERNAME]\AppData\Roaming\sparkreader\config.json like @matoung described:

https://github.com/matoung/SparkReader

for reference, here's the `config.json` i'm using:

```
{
	"settings": {
		"cronjob": "*/10 * * * *",
		"darkMode": "on"
	},
	"accounts": {
		"default": "rss",
		"active": "ttrss",
		"accounts": {
			"rss": {
				"name": "rss",
				"type": "local",
				"username": "",
				"passwd": "",
				"endpoint": "",
				"lastFetchTime": 0
			},
			"ttrss": {
				"name": "ttrss",
				"type": "fever",
				"username": "changeme",
				"passwd": "hunter2",
				"endpoint": "http://10.1.1.3/tt/plugins.local/fever/",
				"lastFetchTime": 1611734918
			}
		}
	}
}
```


![sparkr](https://user-images.githubusercontent.com/7643586/105964813-01ac8d80-6083-11eb-9676-b4241822b98f.PNG)

**Comment by mrgodhani** [comment]
TT-RSS with fever plugin is now supported
