### ISSUE TITLE
Maximize window on Linux

### ISSUE THREAD

**Issue by caipiranima** [hello-efficiency-inc/raven-reader#305]
I don't know how the app works on other systems or if the behavior I found on Linux was expected, but I was not able to maximize the window of the app. This was a little annoying, plus the fact that the app don't show entirely on my screen: I use a resolution of 1366x768, but I have a bar on top of the screen that takes kind of 25px or so.

Tweaking the code a little, I was able to solve this. All the changes are on src/main/index.js. First, I changed the minHeight to a lower value (in my case 600). Then, I added the "maximize role" on this part:
```
{
    role: 'window',
    submenu: [
        { role: 'minimize' },
        { role: 'maximize' },
        { role: 'close' }
    ]
}
```
I'm not making a pull request because I don't know if this is a bug and I chose an arbitrary value for minHeight, but that is my contribution.

**Comment by aksh1618** [comment]
I can confirm facing this.

**Comment by mrgodhani** [comment]
https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v0.6.1 in latest release pressing `ALT+M` would hide the menubar and screen would be maximized.
