### ISSUE TITLE
Possibility to hide toolbar and show it via ALT key

### ISSUE THREAD

**Issue by anonymous133** [hello-efficiency-inc/raven-reader#310]
Please make it possible to hide the Toolbar (Raven Reader, Edit, View, Window) and utilize standard behavior to show it. Like in Firefox the ALT key makes the toolbar visible.

EDIT: I just saw that on KDE the toolbar is hidden. 

So additional information: I'm using i3 window manager on Linux. That might be the reason why it is visible all the time.

**Comment by mrgodhani** [comment]
https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v0.6.1 Fixed in latest key to hide is `ALT+M`
