### ISSUE TITLE
Cannot use RSS URL's with multiple parameters

### ISSUE THREAD

**Issue by mignat** [hello-efficiency-inc/raven-reader#320]
**Describe the bug**
While trying to add a new RSS feed that has multiple parameters in the URL  , those parameters are ignored and the app uses only the first one
**To Reproduce**
1. Go to example URL: 'https://nyaa.si/?page=rss&q=[HorribleSubs]+Black+Clover+[1080p]' (excuse the weebness)
2. Look at the RSS feed list 
3. Add the URL to the APP
4. Observe that the URL that the app requests is 'https://nyaa.si/?page=rss' instead of the full URL

**Expected behavior**
The app should make the request to the complete URL, not just part of it

**Screenshots**
![bug png](https://user-images.githubusercontent.com/30924447/53994255-7cd8c380-413a-11e9-835f-dcba15f864fd.jpg)

**Additional Information**
The URL works as expected  in `RSSowl` so i think this problem is not site related

**Desktop:**
 - OS: Windows 10 64-bit
 - Browser: Vivaldi ( Modified Google Chrome

**Comment by remiq** [comment]
This is an issue with nyaa.si. Their RSS's link is always `https://nyaa.si/?page=rss`, no matter what `q` is.

What raven-reader can do is ignore RSS link provided by RSS file and just use link provided by user.

**Comment by mrgodhani** [comment]
Fixed https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v0.6.4
