### ISSUE TITLE
Error viewing NYTimes RSS feed - Weather replaces whole UI after ~10 seconds

### ISSUE THREAD

**Issue by melek** [hello-efficiency-inc/raven-reader#351]
**Describe the bug**
Most of the UI Disappears after a delay when trying to view a story from a feed, and I can't get it back.

**To Reproduce**
1. Install Raven Reader on Windows (0.4.3)
2. Add 'nytimes.com' rss feed
3. Click on the newest story
4. After about 10 seconds, Observe error; whole panel is replaced by the weather from NYTimes (may be their error?), and I can't see the Raven UI without restarting the app. 

**Expected behavior**
I expect to be able to read the story and continue using the UI.

**Screenshots**
* Before clicking on story: ![image](https://user-images.githubusercontent.com/220149/55576959-4f465200-56c7-11e9-8605-1fb320ab7a40.png)
* Right after clicking on story: 
![image](https://user-images.githubusercontent.com/220149/55576997-64bb7c00-56c7-11e9-87c6-ca3c7be1682f.png)
* ~10 seconds after clicking on story: 
![image](https://user-images.githubusercontent.com/220149/55577024-70a73e00-56c7-11e9-8ad7-826d1a533d03.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: ??? Chrome
 - Version: Raven Reader 0.4.3 for Windows

**Additional context**
I haven't used RSS much, and haven't tried Raven with other feeds yet - just NY Times, so it may be a problem with their feed (though the behavior still feels glitchy).

**Comment by mrgodhani** [comment]
@melek I think it's nature of the type of RSS you used from NY Times. If you use https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/world/rss.xml then it's Articles are rendering fine.

**Comment by melek** [comment]
@mrgodhani Unfortunately, even the better feed you gave me has a similar error where the UI disappears and shows me some small piece of information. In this case, when I click from article to article, after some delay I get this screen:
![image](https://user-images.githubusercontent.com/220149/55598471-b84dba00-5707-11e9-903f-b3aa9d273de7.png)

I get stuck here and have to restart Raven Reader to get other articles, etc.

**Comment by mrgodhani** [comment]
Might be Windows-specific error. Will look into it

**Comment by mrgodhani** [comment]
Should be resolved now.
