### ISSUE TITLE
More configuration options?

### ISSUE THREAD

**Issue by zohozer** [hello-efficiency-inc/raven-reader#438]
I tryed to configure Raven Reader using the "config.json" file but seems to be only a few options that can be configured there:

======================
{
	"settings": {
		"darkMode": "on",
		"cronjob": "* * * * *",
		"oldestArticles": "off"
	},
	"inoreader_token": "{\"access_token\":\"569.......73\",\"expires_in\":86400,\"token_type\":\"Bearer\",\"scope\":\"read\",\"refresh_token\":\"edb.....0d0\"}"
}

==========================

It will be useful to be able to configure somehow the appearance of the interface, like font sizes, colours, the layout, etc.

Maybe some .css theme files that can be used as "themes" will do the trick.

**Comment by mrgodhani** [comment]
@zohozer yes font size and some basic accessibility features are in work. Was busy this days in my day job. But will try to get back to it and finish working on it.

**Comment by zohozer** [comment]
Good to know that this features will be added soon. Thank you.

**Comment by mrgodhani** [comment]
Added couple of config options like font size change + font style change also added couple themes. Closing this now. All is available in latest.
