### ISSUE TITLE
Ability to rename subscriptions, or change their url

### ISSUE THREAD

**Issue by Jack-Chronicle** [hello-efficiency-inc/raven-reader#443]
Would love to be able to rename a feed to something more easily identifiable, or change the url a bit instead of having to add a new subscription and remove the old one

**Comment by mrgodhani** [comment]
In upcoming new version I have included ability to edit name of the Feed.

**Comment by mrgodhani** [comment]
Fixed in https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v0.5.4
