### ISSUE TITLE
Privacy reader

### ISSUE THREAD

**Issue by heavyblack1** [hello-efficiency-inc/raven-reader#444]
I have question
Raven reader use or not cookies which can store telemetry id many websites use this  or user agent or something can track user. 
I ask because i want truly privacy reader.

**Comment by mrgodhani** [comment]
@heavyblack1 There is no cookies it's a desktop app. Neither there is tracking of users installed in this app.

**Comment by heavyblack1** [comment]
Thanks it's great app.

**Comment by mrgodhani** [comment]
Right now although it is a free app. But in future to support on going maintenance of this app we are thinking to make this app paid. But still value of keeping it private and privacy focused would be same with no user usage tracking.
