### ISSUE TITLE
Consider switching global-tunnel-ng to global-agent

### ISSUE THREAD

**Issue by gajus** [hello-efficiency-inc/raven-reader#445]
`global-tunnel-ng` used in this [package](https://github.com/hello-efficiency-inc/raven-reader/blob/9560ef3a5f672c76bdafe6b0dd539f3c9be9ec03/package.json#L103) [does not work in Node v11 and above](https://github.com/np-maintain/global-tunnel#global-tunnel).

If you require a global proxy, consider switching to https://github.com/gajus/global-agent.

The required setup is:

```js
import {
  createGlobalProxyAgent
} from 'global-agent';

createGlobalProxyAgent({
  environmentVariableNamespace: '',
  forceGlobalAgent: true
});

```

**Comment by mrgodhani** [comment]
Fixed in latest release
