### ISSUE TITLE
Ability to copy a source URL of the individual RSS feeds

### ISSUE THREAD

**Issue by d2s** [hello-efficiency-inc/raven-reader#446]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to copy the RSS feed URL of an individual feed subscription.

Even while it almost would be possible to copy an URL path via right-clicking individual feed name in the sidebar, but that is not for the RSS feed itself. Instead user gets an address of the Electron app resource, instead of what could be expected.

<img width="254" alt="2019-07-23-Raven-Reader-sidebar-copy-link" src="https://user-images.githubusercontent.com/135053/61720587-bae42600-ad6f-11e9-9b47-ea88054100d5.PNG">

```
file:///C:/Users/[username]/AppData/Local/Programs/raven-reader/resources/app.asar/dist/electron/index.html#/feed/147db137-41bb-37c9-98a6-a2349254833a
```

**Describe the solution you'd like**
Suggesting that there would be an ability to copy the source URL for individual feeds from a sub-menu.

**Describe alternatives you've considered**
Alternatively there could be a bit better feed management UI, but that would require considerably more implementation work. Even while it is already possible to export all of the feeds at the same time to an OPML formatted XML file, parsing that minified file manually with a text editor is not the most user friendly experience for most people.

**Comment by mrgodhani** [comment]
https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v0.6.0 Added the ability to copy feed in latest release
