### ISSUE TITLE
npm run dev shows "listing directory /" instead of a functioning app

### ISSUE THREAD

**Issue by jcalfee** [hello-efficiency-inc/raven-reader#447]
**Describe the bug**
`npm run dev` use to show a functional app (somewhere around v0.5).  More recently in master and v0.6.1 I just the menus and a folder:

![image](https://user-images.githubusercontent.com/204121/62569810-a7978700-b854-11e9-930e-8224a38184ed.png)

**To Reproduce**
```
npm install
npm run dev
```

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: master and v0.6.1

**Comment by mrgodhani** [comment]
@jcalfee what's the node version and full error output. Also you need `cp config.example.js config.js` from `renderer` folder

**Comment by jcalfee** [comment]
I removed `node_modules` then ran `yarn install`..  After `cp config.example.js config.js`, `yarn dev` does show an error:

```bash
 ERROR in ./src/renderer/config.json
  Module parse failed: Unexpected token e in JSON at position 0 while parsing near 'export const INOREAD...'
```

**Comment by mrgodhani** [comment]
@jcalfee what's the node version when you do `node -v`

**Comment by jcalfee** [comment]
v11.6.0

**Comment by mrgodhani** [comment]
@jcalfee Pushed code fix try again and let me know. I tried v11.6.0 and v12 didn't see same error as you on my end

**Comment by jcalfee** [comment]
Same error

**Comment by mrgodhani** [comment]
@jcalfee ok I misread the error filename is wrong it is `config.js` not `config.json`

**Comment by jcalfee** [comment]
What version of node are you using?

**Comment by mrgodhani** [comment]
I am using v12 but I tested on both 11.6.0 was fine. Looking at your error message there shouldn't be any config.json in renderer folder it's only` config.js`

**Comment by jcalfee** [comment]
If your not seeing an issue we can close for now until I re-visit or this comes up with someone else.  Thanks for looking at this.

**Comment by mrgodhani** [comment]
@jcalfee I think you misunderstood what I said above.

```
ERROR in ./src/renderer/config.json
  Module parse failed: Unexpected token e in JSON at position 0 while parsing near 'export const INOREAD...'
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  SyntaxError: Unexpected token e in JSON at position 0 while parsing near 'export const INOREAD...'
```

In above error you posted it shows error in `/config.json`. `/config.json` shouldn't be a file in renderer folder it's only `config.js`. So compiler is confused with it and picks wrong filename. So if you remove `config.json` it would fix your issue

**Comment by jcalfee** [comment]
Got it .. I swapped the extension when I copied it.  Yes, that fixed it.

**Comment by jcalfee** [comment]
You might want to move that step up in [build-setup](https://github.com/hello-efficiency-inc/raven-reader#build-setup) so that the `cp` appears before `npm run dev`.  I went ad-hock when I saw that `npm run dev` produced that error.
