### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by troe** [hello-efficiency-inc/raven-reader#453]
You can place the translation files on the services:

1. Transifex [transifex.com](https://www.transifex.com/)
2. Weblate [weblate.org](https://weblate.org/)

**Comment by sanawu** [comment]
Just publish a list of keys and people can submit values for the languages

**Comment by Vistaus** [comment]
I support this and will provide the Dutch translation if this gets implemented somehow. Transifex or, alternatively, Weblate as suggested would be bomb, but even barebones manual translation files would be fine.

**Comment by mrgodhani** [comment]
@troe Which language preference do you have?

**Comment by mrgodhani** [comment]
Closing this story. Now we have the locale support. It's unclear from the ticket which language preference is needed. But any help on translation or contribution to it would be very helpful.
