### ISSUE TITLE
Is normalizing rss url necessary?

### ISSUE THREAD

**Issue by remiq** [hello-efficiency-inc/raven-reader#454]
While trying to add new rss url, I've noticed that normalize-url changes valid url into invalid. Is url normalization necessary here?

Valid url:
http://twitrss.me/twitter_user_to_rss/?user=mrgodhani
Invalid url (after normalization):
http://twitrss.me/twitter_user_to_rss?user=mrgodhani

Alternative solution (to removing normalization) for this issue is using normalize-url removeTrailingSlash: false option.

**Comment by mrgodhani** [comment]
Fixed https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v0.6.4
