### ISSUE TITLE
Tray popup menu not working on linux

### ISSUE THREAD

**Issue by hungtcs** [hello-efficiency-inc/raven-reader#455]
[event `right-click`](https://electronjs.org/docs/api/tray#event-right-click-macos-windows) of tray is only work on mac or windows, [this line](https://github.com/hello-efficiency-inc/raven-reader/blob/master/src/main/index.js#L352) pop up context menu when right click is not working on linux. Maybe use [tray.setContextMenu](https://electronjs.org/docs/api/tray#traysetcontextmenumenu) instead.

**Comment by mrgodhani** [comment]
Fixed in https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v0.6.6

**Comment by ArchieMeng** [comment]
This doesn't working again for me at least from 1.0.48.
And if I start it again while the current raven-reader is minimized, some errors received and then closed:
```shell
$ /opt/raven-reader/raven-reader 
(electron) Security Warning: A WebContents was just created with both webviewTag and contextIsolation enabled.  This combination is fundamentally less secure and effectively bypasses the protections of contextIsolation.  We strongly recommend you move away from webviews to OOPIF or BrowserView in order for your app to be more secure
00:45:30.611 › APPIMAGE env is not defined, current application is not an AppImage
(node:1341050) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(Use `raven-reader --trace-warnings ...` to show where the warning was created)
```

Nothing happen if I launch raven-reader again with its window opened.
