### ISSUE TITLE
MacOS brew install?

### ISSUE THREAD

**Issue by ysm0622** [hello-efficiency-inc/raven-reader#456]
Does it support installation using brew on macOS?

**Comment by mrgodhani** [comment]
@ysm0622 Yes, I could support it. Although I am not sure for the part if brew accepts apps that are going to be paid?

**Comment by synhershko** [comment]
@mrgodhani it does

**Comment by mrgodhani** [comment]
https://github.com/Homebrew/homebrew-cask/pull/81851 Just opened PR to add it into Brew. So installing via brew on Mac will be available soon.
