### ISSUE TITLE
Thanks for the RSS reader.

### ISSUE THREAD

**Issue by mrkaban** [hello-efficiency-inc/raven-reader#457]
Hello, thank you very much for such a good program for reading news feeds, and special thanks for distributing the program under the MIT license.

Added your RSS reader to my website ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/rss/raven-reader-rss.html)) about free software (gnu gpl and similar licenses).

Are you planning to translate into other languages? Ready to help with translation into Russian!

**Comment by mrgodhani** [comment]
Not at the moment. For now, would be in English
