### ISSUE TITLE
http://export.arxiv.org/rss/cs won't show it in subscriptions list

### ISSUE THREAD

**Issue by ansorre** [hello-efficiency-inc/raven-reader#462]
**Describe the bug**
Adding 
http://export.arxiv.org/rss/cs
won't show it in subscriptions list, but news are downloaded and shown.

**To Reproduce**
1. add subscription to http://export.arxiv.org/rss/cs
2. news are shown, but subscription is not listed in subscription lists
3. even closing and restarting the app subscription is not listed in subscription lists
4. all other subscriptions so far show correctly in the subscription list, just http://export.arxiv.org/rss/cs won't show

**Expected behavior**
http://export.arxiv.org/rss/cs appears in the subscription list

**Desktop (please complete the following information):**
 - OS: Windows 10

Thanks

**Comment by ansorre** [comment]
Another problem is that even uninstalling the app and manually removing raven stuff rom AppData on windows 10 does not remove the articles from arxiv.org, when you reionstalla the app you find all of them. Is there a way to remove them? Is there a way to cleanup them? Where are this info stored?
Thanks.

**Comment by ansorre** [comment]
Should other have the same problem on windows raven stores it's data in the folder:
C:\Users\<the-user>\.rss-reader

**Comment by mrgodhani** [comment]
<img width="1316" alt="Screen Shot 2020-02-22 at 1 46 56 PM" src="https://user-images.githubusercontent.com/1529009/75097533-d4558680-5579-11ea-9603-f6832ba1eacb.png">
Wasn't able to reproduce in latest version
