### ISSUE TITLE
Article sorting broken

### ISSUE THREAD

**Issue by abuisman** [hello-efficiency-inc/raven-reader#465]
**Describe the bug**

Articles aren't sorted properly:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/27729/82461607-eb453f80-9aba-11ea-9313-b3bb927b970d.png">

**To Reproduce**
1. Add a few feeds.
2. Click on `All feeds`
3. Observe ordering is wrong

**Expected behavior**
I'd expect 08 April 2020 to site above 25 March 2020, etc. 

**Desktop (please complete the following information):**
 - OS: maOS 10.15.4 (19E287)
 - Version Version 0.7.7 (0.7.7)

**Comment by mrgodhani** [comment]
Thanks for reporting this would be sorted in upcoming release

**Comment by abuisman** [comment]
Glad to get the sorting sorted 😄

**Comment by mrgodhani** [comment]
Fixed in v0.7.8
