### ISSUE TITLE
Disabling web security + enabling node integration = security disaster

### ISSUE THREAD

**Issue by yang991178** [hello-efficiency-inc/raven-reader#470]
It seems that `webSecurity` is disabled for the renderer process while `nodeIntegration` is enabled for both the renderer process and webviews. This enables the websites visited through the program to do almost anything to the computer with JS (opening other programs through shell, reading or writing any files, etc.). Since `webSecurity` is disabled, Electron won't really check the TLS certificates for HTTPS connections. Even if a user only visits trusted content through HTTPS, an on-path or in-path attacker can still inject any JS code to the web contents.

**Comment by mrgodhani** [comment]
@yang991178 I am working on revaluating that. Only reason for doing that is for allowing oauth to external API like pocket as oauth happens web based. But thanks for pointing thaf.

**Comment by mrgodhani** [comment]
Made web security turned on. Will continue to work on a fix. There is a flaw in electron-vue somehow it does not work without nodeIntegration.
