### ISSUE TITLE
Manually force-refresh a feed upon selecting it

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#475]
**Is your feature request related to a problem? Please describe.**
Currently there seems to be no way to force Raven Reader to refresh feeds manually. That is, feeds are auto-refreshed based on the time we specify in the Settings window. So if we need to refresh feeds manually, apparently we can't. Of course, there may be a keyboard shortcut for it but if it exists, there's no mention of it in the menus.
**Describe the solution you'd like**
Either add a context menu item so when the Applications key is pressed on a feed, one can select the "Refresh" item to have the feed refreshed. Alternatively, it can be done by pressing Enter on the feed link from the Feeds list.
**Describe alternatives you've considered**
Guess no alternative solutions or keyboard shortcuts exist.
**Additional context**

**Comment by mrgodhani** [comment]
@amirsol81 You can currently refresh feeds. For that, you need to click on the Refresh button as seen below besides the checkmark.

<img width="190" alt="Screen Shot 2020-09-22 at 8 22 52 PM" src="https://user-images.githubusercontent.com/1529009/93950406-6c367100-fd11-11ea-80b8-b1ca04b50802.png">

Thank won't refresh specific feed but would refresh all feeds subscribed to

**Comment by amirsol81** [comment]
@mrgodhani The problem is that the Refresh button or Refresh link isn't announced by screen readers for the visually impaired -- like NVDA and JAWS. As a blind user I rely on these to interact with the app and while everything in the GUI has proper labels and the app itself is awesomely accessible, the refresh button/link isn't announced at all. In fact, I can't figure out where it's located to begin with.

**Comment by mrgodhani** [comment]
@amirsol81 Ah I see ye definitely needs improvement on Accessibility side things. We will work on it

**Comment by amirsol81** [comment]
Thanks for your efforts. Looking forward to the new releases.

**Comment by amirsol81** [comment]
@mrgodhani Has the development of Raven Reader been stalled? Since Raven Reader is the most recognized Electron RSS reader, I thought its development cycles are more vibrant. Apart from this particular issue, if development is ongoing I suggest that issues #478 #477 & #476 also be taken into consideration. Thanks.

**Comment by mrgodhani** [comment]
@amirsol81 Development is not stalled. It's just I am one man army maintaining the application. I will work on those issues but it will take a bit of time.

**Comment by amirsol81** [comment]
@mrgodhani Thanks! Your efforts are truly appreciated. I didn't know that you are the only person working on the app. Actually Raven Reader is so feature-rich that I thought at least a few people are involved. In fact, it's because of its awesome features and almost flawless accessibility that I'm so eager to see these remaining issues fixed.

**Comment by mrgodhani** [comment]
v1.0.8 I have added refresh per feed for that you apparently have to do right-click. The option is available in the context menu
