### ISSUE TITLE
Raven Reader fails to preserve feed categories and groups upon importing OPML files

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#476]
**Describe the bug**
I have an OPML file which has been created -- or exported -- from my list of feeds in Internet Explorer 11. I have several feed categories such as Technology, News, NPR, etc., and each one contains several feeds. When Raven Reader imports them, however, all categories are lost and the app generates a random mix of my feeds. This makes navigation and feed organization quite difficult. Moreover, Raven Reader truncates many of the feed names which, yet again, makes navigation a bit cumbersome.
**To Reproduce**
Simply import my provided OPML file into Raven Reader to duplicate the issues.

**Expected behavior**
I expected to have my feed categories -- or so-called folders -- preserved.
**Screenshots**

**Desktop (please complete the following information):**
Win 10 Pro 64-Bit, Version 2004
Google Chrome 64-Bit
Version 85.0.4183.102
**Smartphone (please complete the following information):**

**Additional context**
[feeds.zip](https://github.com/hello-efficiency-inc/raven-reader/files/5262591/feeds.zip)

**Comment by mrgodhani** [comment]
Fixed in v1.0.5

**Comment by amirsol81** [comment]
@mrgodhani Greetings. I'm running V1.0.5 of Raven Reader. While I can confirm that the issue affecting importing OPML files has been fixed, Raven Reader still tends to truncate feed names/titles inside folders. For instance, inside my News folder/category, when expanded, I have items like "Foreign Policy I...", "National Interes...", "Wall Street Jour...", etc. Since these are truncated, screen readers can't read them properly.
Moreover, the issue of not being able to refresh feeds manually still persists. I just see, or rather hear, a "Refresh All Feeds" button, but don't have a "Refresh Feed" button. Based on what you described in #475 the button is apparently there but isn't read or detected by screen readers. Any chance of kindly providing a fix for it as well?
Thanks.

**Comment by mrgodhani** [comment]
@amirsol81  In regards to Refreshing feeds. Button "Refresh All Feeds" would refresh all the subscribed feeds in the list instead of the specific. I can add a specific feed refresh that would be when you do right click on feed select a menu item from there.

**Comment by amirsol81** [comment]
@mrgodhani Refreshing single feeds manually would be an awesome idea. Moreover -- and this might be due to my lack of familiarization, is it possible to ask Raven Reader to update each feed on a different schedule apart from the global schedule? For instance, I might set my global refresh rate to 1 hour but I might want to refresh Feed A every 5 minutes and Feed B every 15 minutes. Is it doable at the moment? If not, I'd appreciate it if such a feature is implemented.

**Comment by mrgodhani** [comment]
@amirsol81 In regards to setting a schedule. You can set that in the settings modal and choose refresh interval. After setting that it would refresh depending on that interval. You can access the settings modal window by going to Raven Reader Menu Item > Settings or press Ctrl + ,. A menu item on windows would be at the top. That schedule settings would apply for refreshing all feeds vs specific ones.

**Comment by amirsol81** [comment]
@mrgodhani So do you mean that setting up individual schedules for each feed isn't possible at the moment?

**Comment by mrgodhani** [comment]
@amirsol81 At the moment yes it won't be possible.  Will consider for a future feature. Bear in mind that all the processing is done locally at the moment so it could get very heavy if you have more feeds. There is no external database and so far haven't seen any other desktop app doing it.

**Comment by amirsol81** [comment]
@mrgodhani You are right. But since Internet Explorer 11 does it with its built-in RSS reader, I used to think that it might be doable rather easily.

**Comment by amirsol81** [comment]
@mrgodhani I'd appreciate it if you could take care of the "feed truncation" issue which makes it almost impossible to see which feed has the focus. For instance, two of my feeds are titled "Weekend Edition S...", and "S..." might refer to "Saturday" or "Sunday". Since they are truncated, I can't tell which one has the focus.

**Comment by mrgodhani** [comment]
@amirsol81 That should be fixed now just did one more release in 1.0.6

**Comment by amirsol81** [comment]
@mrgodhani Mega thanks for the fix! It works like a charm. For the first time I'm enjoying a fully functional and accessible full-text RSS reader on Windows courtesy of your inimitable efforts! Keep up the good work.
