### ISSUE TITLE
Raven-Reader fails to refresh many Google News RSS feeds

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#477]
**Describe the bug**
Raven-Reader doesn't refresh many Google news RSS feeds and the Unread count for them remains 0.
**To Reproduce**
Just add the following Google News feed URL to Raven-Reader and try refreshing it: https://news.google.com/rss/search?gl=US&hl=en-US&ceid=US:en&q=Biden
You may also want to import my attached OPML file as it contains many more examples of Google News RSS feeds which aren't refreshed at all.
**Expected behavior**
Raven-Reader should update all Google News feeds -- like any other RSS feed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 64-Bit, Version 2004. Also tested on Win 7 64-Bit.
 - Browser: Google Chrome 64-Bit
 - Version 85

**Smartphone (please complete the following information):**

**Additional context**
I tested with the latest 1.02 release of Raven-Reader downloaded from its website.
[feeds.zip](https://github.com/hello-efficiency-inc/raven-reader/files/5271399/feeds.zip)

**Comment by mrgodhani** [comment]
Should be fixed now in v1.0.4 latest release

**Comment by amirsol81** [comment]
@mrgodhani Thanks for the fix, and also thanks for diligently going through the issues!
I'd really appreciate it if you could also kindly take care of bugs #475 and #476 which I reported. If they're fixed, using the app from the perspective of a blind person could be hugely enhanced.
