### ISSUE TITLE
Raven Reader doesn't display the publication time for articles

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#480]
**Describe the bug**
Simply put, Raven Reader only displays the date for articles, and the publication time isn't displayed -- quite oddly.

**To Reproduce**
Simply take a look at your article titles for a feed. You'll see the date, like 17 October 2020, listed near the title not the time.

**Expected behavior**
The time should be displayed next to the date.

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 64-Bit V2004
 - Browser: Google Chrome 86

**Comment by mrgodhani** [comment]
Fixed in 1.0.7

**Comment by amirsol81** [comment]
@mrgodhani Awesome job! Thanks!
