### ISSUE TITLE
1.0.4 -> 1.0.5 update removed all subscriptions (Windows)

### ISSUE THREAD

**Issue by eiriksn** [hello-efficiency-inc/raven-reader#481]
**Describe the bug**
Yesterday I did a fresh install of 1.0.4 and set up at least 3 different subscriptions and 2 custom categories. Today the app started installing an update to 1.0.5, and after the app restarted there were no subscriptions or custom categories shown.

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 2004 (OS Build 19041.572)

**Comment by mrgodhani** [comment]
@eiriksn Yes that is because we had to swap DB with a different adapter that is more performant

**Comment by eiriksn** [comment]
@mrgodhani That feels a bit heavy-handed for a post-1.0 update that installs itself without a prompt. Is there no way to restore the lost data?

**Comment by mrgodhani** [comment]
@eiriksn Working on a patch that would migrate existing data will release it shortly

**Comment by mrgodhani** [comment]
Did a release should get fixed in 1.0.6. For context, all data is stored locally in IndexDB. Since we changed DB now to use Lovefield instead of NeDB is the reason why this issue occurred. Reopen if it didn't fixed.
