### ISSUE TITLE
Accessibility improvement: displaying the extracted text of articles inside a frame

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#482]
* Problem: When an article is selected for reading, Raven Reader displays it after the last article on the screen, meaning we should skip all headings via pressing the letter H several times via our screen readers to reach the extracted text for the article. This is rather time-consuming.
* Solution: if the extracted text for the selected article is wrapped inside a frame, we can simply press the letter M to jump to the extracted text for the article, skipping all articles in between. In screen readers, the letter M can be used to jump to the next Frame on an HTML page. So the <iframe> tag can be used for that purpose.
*Alternatively the Region landmark A role="region" attribute can be used to wrap the extracted text. Regions can also be navigated and located easily by screen readers for Windows and Mac -- if the latter is also of concern.

**Comment by mrgodhani** [comment]
Should be now fixed on v1.0.8

**Comment by amirsol81** [comment]
@mrgodhani Awesome! Will try V1.0.8 today.
