### ISSUE TITLE
[FEATURE REQUEST] Embedded videos

### ISSUE THREAD

**Issue by jGsch** [hello-efficiency-inc/raven-reader#485]
**Is your feature request related to a problem? Please describe.**
I use RSS feeds to follow channels on youtube. But for the moment, these feeds don't display anything at all and you have to click on `View as original` to access the video which is not very practical.

**Describe the solution you'd like**
An embedded player to watch youtube videos (even [invidious](https://github.com/iv-org/invidious) videos if possible!)

**Additional context**
fedora 32
raven reader 1.0.8

**Comment by mrgodhani** [comment]
Embedded videos are showed in some articles right now. It all depends on the parser we use that is Mercury Parser. Will investigate further.

**Comment by sanawu** [comment]
No autoplay thanks

**Comment by mrgodhani** [comment]
Supported in v1.0.21
