### ISSUE TITLE
Image-caching and loading should be configurable not automatic

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#487]
*Issue:
Raven Reader automatically caches and loads images the way it auto-caches text. However, image-caching/loading should be configurable so that it can be disabled if needed. Under most circumstances, viewing images is not needed for many users as it just consumes time and bandwidth.
*To Reproduce:
Simply refresh your feeds. Images are displayed. Also the Settings window doesn't provide an option to disable image loading/caching.open your 
*Expected behavior:
Image-loading/caching should be configurable -- either globally in the Settings window or on a per-feed basis.
 - OS: Win 10 Pro 64-Bit V2004
 - Browser Google Chrome V86

**Comment by mrgodhani** [comment]
Added option to remove images from an article in preference settings.
