### ISSUE TITLE
Serious glitch fetching full text of articles which results in partial fetching

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#489]
**Describe the bug**
Under some circumstances, Raven Reader fails to fetch the full text of articles. This results in a partial fetch rather than a full fetch.
For instance, I was reading the following article in Raven Reader: https://www.wired.com/story/left-right-speak-different-languages-literally It belongs to the following feed: http://feeds.wired.com/wired/index However, displays maybe half of the article in its full text render, up to this sentence: "He notes that the Carnegie Mellon paper considers “BLM” (Black Lives Matter) and “ALM” (all lives matter) a “translatable” pair, akin to “mask” and “muzzle.”"
Obviously this sentence doesn't end the actual article.

**To Reproduce**
1. For this example you should subscribe to http://feeds.wired.com/wired/index first.
2. Then open the following article in Raven Reader: "The Left and the Right Speak Different Languages—Literally"

**Expected behavior**
Raven Reader should display the full text, ending in this sentence: "“Analyzing the spectrum of political discourse makes more sense.”"
Moreover, IMO Raven Reader should have a facility to report text extraction issues within the app itself.

**Desktop (please complete the following information):**
 - Win 10 Pro 64-Bit, V2004
 - Browser: Google Chrome
 - Version: 86

**Additional context**
Raven Reader V1.0.9.0

**Comment by mrgodhani** [comment]
I would close this as it is really not bug for Raven. Raven uses https://github.com/postlight/mercury-parser. So it would be good to log that issue there.

**Comment by amirsol81** [comment]
@mrgodhani Thanks -- I'll do it. But since you want to release Raven Reader Pro, any chance of using a better -- perhaps paid -- text parser for that? I'm beginning to notice more and more parsing glitches with Mercury, and I'm sure they don't fix bugs promptly.

**Comment by mrgodhani** [comment]
@amirsol81 Not much interest around people paying for apps. We had this app paid before for couple months that didn't quite workout. So Pro won't be soon.

**Comment by amirsol81** [comment]
@mrgodhani Wish it were not the case. Few weeks ago I paid $9.99 for my favorite RSS reader on iOS, Lire, and I can't be happier even with its second update over the past few years, given its features and versatility. Wish you could adopt such a business model if feasible.
BTW I tried reporting the Mercury bug but their bug report form is quite complicated: Mercury version, Mercury node, etc. -- all beyond my ken.

**Comment by amirsol81** [comment]
@mrgodhani My tests indicate that almost all articles from Wired are affected by this Mercury glitch: http://feeds.wired.com/wired/index For instance, I just encountered it while reading this article: https://www.wired.com/story/what-comes-after-the-international-space-station
This is really annoying. Unfortunately I can't report the bug on Mercury's Github page as it requires some technical info -- Mercury version, Node, etc. So would you please kindly report it there? Alternatively, would it be possible to switch to a more versatile parser?

**Comment by mrgodhani** [comment]
Issued ticket https://github.com/postlight/mercury-parser/issues/590.

Better versatile parser cost us around $300/month and unfortunately we don't have budget to spend that much.

**Comment by amirsol81** [comment]
@amirsol81 Thanks! I also commented there.
So one day in case Raven Reader Pro is released along with a more versatile parser, I'm definitely in! Even in its current form, Raven Reader has been a terrific godsend as nothing can match its features and accessibility on Windows.

**Comment by mrgodhani** [comment]
@amirsol81 One thing to note wired.com also has subscription so it block parser to read and extract full content. In those cases we cannot control anything.

**Comment by amirsol81** [comment]
@mrgodhani Well, my favorite feed reader on iOS, Lire, extracts Wired articles successfully. Granted, it costs $9.99, and the developer says that he uses his own parser that he's been tweaking since 2012. But it apparently indicates that a better parser can do the job.

**Comment by amirsol81** [comment]
@mrgodhani Here's yet another Mercury Parser shortcoming. GSM Arena, http://www.gsmarena.com/rss-news-reviews.php3 publishes reviews of phones from time to time. These reviews are multi-page, meaning users should read 6 or 7 pages in order to see the whole review. However, Mercury only displays the first 2 pages of the review in its extracted text. Check this article, for instance: https://www.gsmarena.com/poco_f2_pro_long_term-review-2186.php
For the record, again my RSS Reader on iOS, Lire, catches and displays all pages, so despite all odds, I just hope Mercury developers do pay attention to these bug reports. I do know other websites which publish multi-page reviews and articles, but haven't tested them against Mercury.
