### ISSUE TITLE
[ Documentation ] There is no renderer/config.example.js

### ISSUE THREAD

**Issue by oktayaa** [hello-efficiency-inc/raven-reader#490]
From the github readme.

# copy config.example.js in renderer to config.js by executing cp config.example.js config.js and set Mercury parser token
cp src/renderer/config.example.js src/renderer/config.js

I just cloned the repo and there is no  config.example.js or src/renderer directory.

**Comment by mrgodhani** [comment]
Thanks for catching you don't need to set Mercury Parser token any more.
