### ISSUE TITLE
Thoughts on web version of raven reader?

### ISSUE THREAD

**Issue by mrgodhani** [hello-efficiency-inc/raven-reader#492]
Hi

I am thinking on working on web version of raven reader. I need help on getting your opinions if this is something that would be useful. 

Here are some of the benefits:

- Synchronized feeds/articles across all devices including mobile (If app is made PWA)
- Helps ability to enhance data storage, parsing of articles etc 
- More innovative features could be added.

Downside, till now raven reader was open without any user login. In this route it would need to have user login/pass in desktop app.

Let me know your thoughts and opinions in this thread thank you.

**Comment by sanawu** [comment]
Well, I found Raven because I was leaving web readers, best of luck

**Comment by amirsol81** [comment]
@sanawu Sorry but why is your tone so harsh? The developer, who is IMO doing a great job on the accessibility side and does listen to our suggestions, has put forward a suggestion. Accepting or rejecting his line of thought can be done more elegantly IMO.

**Comment by amirsol81** [comment]
@mrgodhani To be honest with you, I'd rather have a local RSS reader -- even a paid one -- with a better parser for text extraction, and with features like opening/accessing multiple articles, altering the refresh rate separately per feed, etc. Quite surprisingly, all of these are features which many RSS readers for iOS and Mac provide and many of them are also accessible. So I wonder why these can't be done for Windows or why no one has done it yet.
As for web-based RSS readers, I've tried many of them, but almost all of them have mild to serious issues. So even on iOS, I use Lire which supports local feeds as well as many syncing services.

**Comment by sanawu** [comment]
> @sanawu Sorry but why is your tone so harsh? The developer, who is IMO doing a great job on the accessibility side and does listen to our suggestions, has put forward a suggestion. Accepting or rejecting his line of thought can be done more elegantly IMO.

When there's a plan to monetise it and wants to online OUR data via a login wall, oh boy slapping him with a GDPR violation will cost him more from what I see from the quality of this

How about ZERO ACCESS ENCRYPTION to protect our data from him?

**Comment by mrgodhani** [comment]
Sounds clear no web. @sanawu thanks for your critical opinion. I have 1 question why even try Raven if Feed Reader beats it?

**Comment by sanawu** [comment]
Hoped it would be better; I was proven wrong in it's current state and worrying plans to put me online, which is why I am moving back to a local reader, I made the mistake of using an online feeder service when stupid me, no need for that, it's my data local is perfectly fine, and with tech's data history proven to be damaging, I am now in the process of reducing dependence on online stuff that is quite capable to be done locally
