### ISSUE TITLE
Reopen this bug, this is not fixed and is not working in 1.0.11

### ISSUE THREAD

**Issue by sanawu** [hello-efficiency-inc/raven-reader#493]
https://github.com/hello-efficiency-inc/raven-reader/issues/491

**Comment by mrgodhani** [comment]
Try again should be fixed in 1.0.12

**Comment by sanawu** [comment]
It is not fixed in 1.0.12

**Comment by mrgodhani** [comment]
Cannot reproduce. Cannot help much if you don't provide anything.

Following is feedly exported OPML.

[feedly-4a284637-516a-4ca9-8cbf-8889167bc1a8-2020-10-31.opml.zip](https://github.com/hello-efficiency-inc/raven-reader/files/5468983/feedly-4a284637-516a-4ca9-8cbf-8889167bc1a8-2020-10-31.opml.zip)

Working screen:
![Uploading Screen Shot 2020-10-31 at 7.45.01 AM.png…]()
