### ISSUE TITLE
Request for SVG icon file for the Raven Reader logo (without text)

### ISSUE THREAD

**Issue by sanawu** [hello-efficiency-inc/raven-reader#494]
Request for SVG icon file for the Raven Reader logo (without text)

**Comment by mrgodhani** [comment]
@sanawu Just curious on why do you need logo?

**Comment by sanawu** [comment]
To use on my desktop environment launcher for the AppImage

**Comment by mrgodhani** [comment]
[raven-logo-icon.svg.zip](https://github.com/hello-efficiency-inc/raven-reader/files/5468989/raven-logo-icon.svg.zip)
