### ISSUE TITLE
New feature: 1-minute or 2-minute feed refreshes

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#495]
**Is your feature request related to a problem? Please describe.**
I have some news-oriented RSS feeds, like http://www.dailymail.co.uk/wires/index.rss which send out a good number of new articles -- maybe a couple of articles per minute. However, with Raven Reader and its 5-minute refresh option, oftentimes I'm forced to refresh all feeds manually in order to get new articles from this and similar feeds.

**Describe the solution you'd like**
It would be useful if Raven Reader could allow 1-minute or 2-minute refreshes in the Setting window to add to the current 5-minute refresh rate.

**Describe alternatives you've considered**
Another solution would be allowing per-feed refreshes and 1 or 2-minute refreshes per feed. But Raven Reader doesn't support feed-based refreshes, so the first solution would be more appropriate.

**Comment by mrgodhani** [comment]
Added in 1.0.14

**Comment by amirsol81** [comment]
@mrgodhani Huge thanks!
