### ISSUE TITLE
Exporting Subscriptions not working

### ISSUE THREAD

**Issue by Ruudss** [hello-efficiency-inc/raven-reader#496]
**Describe the bug**
"Export Subscriptions" button does not do anything when pressed 

**To Reproduce**
1. Go to 'Import and Export'
2. Click on 'export Subscriptions'

Nothing happens.

**Expected behavior**
I don't know, I guess it should ask where to save the file or open the export folder?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Raven Reader v 1.0.14

**Comment by mrgodhani** [comment]
When you export subscriptions, there should be a notification. And exported items would be available in the downloads folder.

**Comment by Ruudss** [comment]
> When you export subscriptions, there should be a notification. And exported items would be available in the downloads folder.

Hello mrgodhani thank you for the quick reply.

There is no notification and nothing shows up in the download folder.

**Comment by mrgodhani** [comment]
<img width="461" alt="Screen Shot 2020-12-13 at 9 44 52 PM" src="https://user-images.githubusercontent.com/1529009/102036194-36dd7480-3d90-11eb-8392-d858593ff528.png">

Was not able to reproduce on Windows 10. I can see the notification on bottom right.
