### ISSUE TITLE
Raven Reader 1.0.17 no longer refreshes my feeds

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#500]
Everything was working with Raven Reader 1.0.16, but as soon as I updated to 1.0.17 this morning, my feeds no longer refresh. I'm on Windows 10 Pro 64-Bit, V2009. I've also restarted my notebook but that hasn't resolved the issue. Really pesky bug!

**Comment by mrgodhani** [comment]
@amirsol81 You will have to save the preference or cron settings again and that would fix your issue. We just added encryption because of feedbin integration

**Comment by amirsol81** [comment]
The Preferences tab doesn't have a Save button -- it just has a Close button. But my feeds still aren't refreshed after selecting the Close button. Any easy solutions?

**Comment by mrgodhani** [comment]
@amirsol81 preference window would save automatically. Do you get windows notification? What is your opml feed export if you can provide that

**Comment by amirsol81** [comment]
I get no notifications for feed refreshes as nothing gets refreshed at all. The exported OPML file is attached.
[subscriptions.zip](https://github.com/hello-efficiency-inc/raven-reader/files/5739923/subscriptions.zip)

**Comment by mrgodhani** [comment]
@amirsol81 Just trying your exported feed with 1 minute cron job. Seems to be working. I have tested on Windows 10. And I hear notification sound every 1 min that feeds are refreshed.

**Comment by amirsol81** [comment]
@mrgodhani The issue still persists and I just encountered on another Win 10 64-Bit machine. It is a 1.0.17-specific issue, so any solutions or work-arounds?

**Comment by mrgodhani** [comment]
@amirsol81 Not able to reproduce the issue on Windows 10 64 bit machine for 1.0.17. The feed is refreshing fine and I see notifications.

Feeds are refreshing when doing manually, via cron job or manually refreshing specific feed

**Comment by amirsol81** [comment]
@mrgodhani Quite interestingly, I just noticed that I no longer have the "Refresh feed" option when I press the Applications key on feed addresses. I just have "Copy feed link" and "Mark as read". This is the case on both Windows 10 Pro 64-Bit machines. I did have it with 1.0.16 and some older releases.

**Comment by mrgodhani** [comment]
@amirsol81 Do you have feedbin connected? Refresh feed won't show if the feed is from Feedbin

**Comment by amirsol81** [comment]
@mrgodhani No, I don't have a Feedbin account.

**Comment by mrgodhani** [comment]
@amirsol81 ok Will look into it and should be fixed in new release

**Comment by amirsol81** [comment]
@mrgodhani Thanks -- much appreciated.

**Comment by mrgodhani** [comment]
@amirsol81  should be fixed in new release

**Comment by amirsol81** [comment]
@mrgodhani Thrilled to report that Raven Reader 1.0.18 has resolved my feed refresh issues. Thanks again for your efforts.

**Comment by amirsol81** [comment]
@mrgodhani I'm using Raven Reader 1.0.21, and the "Refresh All Feeds" button doesn't work, yet again. I can refresh feeds manually, but the app never refreshes feeds automatically -- even after selecting the "Refresh All Feeds" button manually.
V1.0.18 used to work properly, so I'm wondering how the app becomes so instable after upgrading to new releases. I really depend on your awesome app on a daily basis, so if it keeps displaying such issues so frequently, I'm afraid I have to seek another more stable solution.

**Comment by mrgodhani** [comment]
@amirsol81 Fixed in latest
