### ISSUE TITLE
Portable

### ISSUE THREAD

**Issue by sick13** [hello-efficiency-inc/raven-reader#504]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrgodhani** [comment]
Sorry, don't understand the issue here closing the ticket.

**Comment by sick13** [comment]
hmmm...something did not register,i typed all explaining what i mean...anyway long story short

By portable i meant Portable Application,so we can store it on a USB and all configuration files stored in the same folder

**Comment by mrgodhani** [comment]
I see you mean backing up data basically

**Comment by sick13** [comment]
no i mean running the application without installing it,unzip and run all the files needed would be in one folder witch can be moved to anywhere,and the program would not create them in program data folder or anywhere else

https://en.wikipedia.org/wiki/Portable_application

**Comment by TCB13** [comment]
+1 on this. A portable version would be nice.

**Comment by mrgodhani** [comment]
Windows portable build is now available for latest version https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v1.0.40
