### ISSUE TITLE
can not import my opml 

### ISSUE THREAD

**Issue by Motocycle347** [hello-efficiency-inc/raven-reader#505]
generated by quiterss Version 0.19.4 (21.04.2020)
Revision 3904
raven version 10.23

import bar stops at approiv 95%

**Comment by mrgodhani** [comment]
@Motocycle347 Can you send your exported opml from quiterss?

**Comment by Motocycle347** [comment]
thank you

**Comment by mrgodhani** [comment]
Should be fixed in the new release. If not please send the opml file to further investigate.

**Comment by Motocycle347** [comment]
The version that is to be downloaded is the same as I allready have.

**Comment by Motocycle347** [comment]
this is the file that will not import sent it before

[ira.zip](https://github.com/hello-efficiency-inc/raven-reader/files/5759381/ira.zip)

**Comment by mrgodhani** [comment]
@Motocycle347  fixed in 1.0.25

**Comment by Motocycle347** [comment]
Currenly the Website has 1.0.23 not 1.0.25

**Comment by mrgodhani** [comment]
@Motocycle347 sorry page was cached. check now again.
