### ISSUE TITLE
Folders not imported via InoReader

### ISSUE THREAD

**Issue by drod3763** [hello-efficiency-inc/raven-reader#508]
**Describe the bug**
I have a bunch of Inoreader feeds sorted into folders, when I synced the feeds were imported but the folders were not. As I understand it from looking at the issues, folders should be supported but I am not even seeing the option to create one.

**To Reproduce**
1. Install raven-reader via brew using the command from the readme.
2. Go to Settings -> Sync Account
3. Select Inoreader
4. Approve the connection

**Expected behavior**
Feeds are synced along with any folders

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Version 1.0.23 (downloaded via brew as per instructions)

**Comment by mrgodhani** [comment]
@drod3763  Folders currently are in WIP for all services

**Comment by mrgodhani** [comment]
Supported in latest version
