### ISSUE TITLE
Maximize Button\Options not Working Under Linux

### ISSUE THREAD

**Issue by RuthlessRuler** [hello-efficiency-inc/raven-reader#509]
**Describe the bug**
Clicking on Maximize Button, right click maximize & Alt + M maximize are not working.
I'm on 1366x768 screen and the program starts in higher resolution thus making it unusable. 
I hope this gets fixed soon.

**To Reproduce**
1. Launch The Raven Reader.AppImage
2. Click on Maximize Button
3. Window Doesnt maximize/fit to current resolution

**Expected behavior**
Application Maximizes to display resolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/20885012/103437675-337f2f80-4c50-11eb-8e2e-11144247fad8.png)

**Desktop**
 - OS: Manjaro 20.2 XFCE
 - Version: 1.0.24

**Additional context**
Also, fallback Icon in Panel is shown instead of showing Raven's. Same in application switcher/etc.

**Comment by Danhicsuntdracones** [comment]
Same issue here on a 1920x1080 screen, the app window is larger than the screen.
There is no maximize button on the top right panel, and trying to resize the app window by manually dragging the corners doesn't work, the window size won't change.

- OS: Linux Mint 20
- AppImage version 10.0.26

**Comment by bituser222** [comment]
I'm also experiencing this issue. The window is too large,  Alt+M won't work, it will not maximize and there is no maximize option/button. However, full screen does work.

- OS: Manjaro 21.2 Gnome
- Version: 1.0.72-1 (from the AUR)
