### ISSUE TITLE
How do I sync with Inoreader

### ISSUE THREAD

**Issue by crazyyzarc** [hello-efficiency-inc/raven-reader#511]
I do not see any option to sync with Inoreader?! How do I do it, but without importing .opml files

**Comment by mrgodhani** [comment]
It would be inside preference. If you press `ctrl + ,` on Linux/Window or `Cmd  + ,` you will see modal window. And inside modal window you will see sync accounts section.

**Comment by crazyyzarc** [comment]
`ctrl + ,` doesn't work on 0.6.6, because I do not get a sync account section. I've pressed `ctrl + ,` on preference and home window

![2021-01-05 14_28_07-Raven Reader](https://user-images.githubusercontent.com/4954535/103652302-32594580-4f63-11eb-9d80-2d1a6741d591.png)

**Comment by crazyyzarc** [comment]
> 
> 
> @crazyyzarc It would be inside preference. If you press `ctrl + ,` on Linux/Window or `Cmd + ,` you will see modal window. And inside modal window you will see sync accounts section.
> 
> Preference option is when you click on `Raven Reader` on top bar.

@mrgodhani `ctrl + ,` doesn't work on 0.6.6, because I do not get a sync account section. I've pressed `ctrl + ,` on preference and home window

![2021-01-05 14_28_07-Raven Reader](https://user-images.githubusercontent.com/4954535/103652556-8ebc6500-4f63-11eb-8ac5-cd71f48e05a6.png)

**Comment by mrgodhani** [comment]
@crazyyzarc You will need to download latest from https://ravenreader.app

**Comment by mrgodhani** [comment]
Current version is 1.0.26

**Comment by crazyyzarc** [comment]
> 
> 
> @crazyyzarc You will need to download latest from https://ravenreader.app

ah okay I've downloaded it from github releases. Thanks
