### ISSUE TITLE
BazQux Reader sync via Google Reader API

### ISSUE THREAD

**Issue by vshabanov** [hello-efficiency-inc/raven-reader#514]
[BazQux Reader](https://bazqux.com) supports Google Reader API (here are the [docs](https://github.com/bazqux/bazqux-api)).

I've tried to sync with it in Raven (latest macOS version) and it just does not work. Settings screen goes blurry and never restores. Restarting Raven does not help. No feeds, no articles after clicking on sync button.

I'm a developer of BazQux Reader and looking into the logs I see that Raven successfully authorizes, makes few requests and fetches some articles, so it's not a connection issue.

Since you already support Inoreader you could try to use the same code for BazQux Reader and The Old Reader (they all use Google Reader API).

Few remarks:
* You pass email & password as query parameters (part of the URL) to /ClientLogin. It makes them visible in server logs. Better to use POST for them.
* You send `c=null` parameter when there is no continuation. It's invalid continuation. I've added a workaround for such cases but it's better to not send `c=null` at all.
* Syncing algorithm is suboptimal. There's a [better way](https://github.com/bazqux/bazqux-api#the-right-way-to-sync) to sync (it applies to all services with Google Reader API and I think to Feedly too).

**Comment by mrgodhani** [comment]
@vshabanov thanks for the suggestion will change the logic for sync and look into google reader api. That was only tested with FreshRSS

**Comment by mrgodhani** [comment]
Made some fixes and improved syncing based on what you mentioned in the new version.

**Comment by vshabanov** [comment]
Great. Thank you for implementing new sync.

There are several issues:

* Existing item contents are redownloaded on each sync (I haven't read anything and Raven fetches same 5k unread items again).

* If I mark item read in BazQux it will stay unread in Raven after sync.

* If I star item and then unsubscribe from feed Raven will hang on first sync (after clicking "Connect"). Next syncs seems to work fine. It's common situation to have old starred items from feeds people no longer follow and it breaks first sync.

* There is a test account in BazQux with username "bigbig" and password "bigbig". It has xkcd feed with 500 unread items. For some reason Raven only syncs 499 items from it.

* It would be nice to show syncing process (rotating sync icon) and syncing progress (show new unread items after each batch not after final sync)

* After clicking "Disconnect" on Google Reader API account and clicking "Connect" old feeds appeared while I was entering URL and credentials. Seems that "Disconnect" does not clean DB (and why it appeared before I've clicked "Connect"?).

* "Disconnect" and "Clean data" remove feeds but not folders.

* Unrelated to main issue, but I needed to click "older articles first" on and off to see new articles first.

* And it's better to show number of unread items for feeds instead of total number (I was surprised that unread counts do not update before I understood that they're total counts).

**Comment by mrgodhani** [comment]
Great Feedback @vshabanov 

For below point what suggestion you have on how to handle?

Existing item contents are redownloaded on each sync (I haven't read anything and Raven fetches same 5k unread items again).

**Comment by vshabanov** [comment]
You should have some mapping between articles in your database and article IDs in BazQux. Then when you fetch unread&starred ids you only download articles that are missing in your local DB and remove articles which IDs are no longer exists in BazQux (and fix unread&starred state in your DB so it corresponds to what you've got from BazQux).

That's the whole point of syncing — only download what's needed. If there's no new articles then the whole sync is only 3 calls: authorize (and you could cache token for two weeks or just reauthorize when you get HTTP 401), fetch unread ids and fetch starred ids.

BTW: I've made your account forever free so you could test it whenever you want.
