### ISSUE TITLE
Truncated publication title despite sufficient space

### ISSUE THREAD

**Issue by dandv** [hello-efficiency-inc/raven-reader#517]
**To Reproduce**
1. Add http://feeds.arstechnica.com/arstechnica/tech-policy
2. Click on an article
3. Notice the `Policy – Ars Technic...` is truncated, even though there's plenty of space to display the whole name.

**Screenshots**
![image](https://user-images.githubusercontent.com/33569/104583129-dc406e00-5604-11eb-8a77-923c0047cc0c.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Browser ??? - what is this referring to?
 - Version 1.0.28

**Comment by mrgodhani** [comment]
Fixed in latest release 1.0.29
