### ISSUE TITLE
Share icon - copy to clipboard

### ISSUE THREAD

**Issue by dandv** [hello-efficiency-inc/raven-reader#518]
**Is your feature request related to a problem? Please describe.**
I was reading an article in full web view, and I wanted to share it with my friend via this chat app we use. To my stupefaction, I couldn't find a way to get the article's URL!

**Describe the solution you'd like**
Sharing by copying the link to the clipboard works ANYWHERE. It should be front and center, easily discoverable.

**Describe alternatives you've considered**
:man_shrugging:

**Comment by mrgodhani** [comment]
You could do right-click on the article list and copy the link. I have added a copy link now in article detail under the share icon dropdown as well.

Fixed in 1.0.29 release
