### ISSUE TITLE
How do I add Pocket to Raven reader?

### ISSUE THREAD

**Issue by fyreswan** [hello-efficiency-inc/raven-reader#519]
How do I add Pocket to Raven reader please?

**Comment by mrgodhani** [comment]
@fyreswan Pocket integration is only for saving the article.

You can connect it by going to Preferences or Command/ctrl + ,


After connecting you will see option for pocket in sharing icon when you read article at the top bar.

**Comment by fyreswan** [comment]
Thank you!
