### ISSUE TITLE
Unable to subscribe to specific RSS feed

### ISSUE THREAD

**Issue by BlueManCZ** [hello-efficiency-inc/raven-reader#523]
**Describe the bug**
I'm unable to subscribe to this RSS feed: https://www.formule.cz/formule/rss/. I'm sure it worked in earlier versions. There is no error in the output log.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on Add
2. Insert https://www.formule.cz/formule/rss/
3. Press enter
4. Click subscribe

**Expected behaviour**
There is no error, so feed should be subscribed and added to the left panel.

**Screenshot**
![Snímek z 2021-02-12 18-34-14](https://user-images.githubusercontent.com/17854950/107801859-ec14b480-6d60-11eb-96a4-815a9dd95167.png)

**Desktop:**
 - OS: Gentoo Linux 5.4.92-gentoo
 - Raven Reader version: 10.0.37

**Comment by mrgodhani** [comment]
Fixed in v1.0.38
