### ISSUE TITLE
Unable to update hackernews feed

### ISSUE THREAD

**Issue by danielwangksu** [hello-efficiency-inc/raven-reader#524]
**Describe the bug**
Tried to subscribe to https://news.ycombinator.com/rss. The link works with other RSS feeder without issue, but with raven reader it does not get updated no matter how many times I click `update all feeds`. I tried to delete it and resubscrible and get the same result. My current Hacker News feed forever stuck on Feb 3rd, the day I subscribed it.

This is on MacOS 11.2.1, Raven Reader 1.0.33

**Comment by mrgodhani** [comment]
@danielwangksu Do you want to download latest version? It is 1.0.37. Just tested it and it works.

<img width="1512" alt="Screen Shot 2021-02-13 at 7 37 28 AM" src="https://user-images.githubusercontent.com/1529009/107850161-5c0d5400-6dce-11eb-9ca3-cf2fe77135b8.png">

**Comment by danielwangksu** [comment]
Thank you @mrgodhani

**Comment by danielwangksu** [comment]
I've having the same issue with latest version 1.0.38 and 1.0.39. The subscription cannot be updated.
