### ISSUE TITLE
Feature Request: Miniflux sync support

### ISSUE THREAD

**Issue by tandy-1000** [hello-efficiency-inc/raven-reader#525]
Raven has support for the Google Reader API but Miniflux does [not yet](https://github.com/miniflux/v2/issues/734) have support for the Google Reader API.

If possible it would be nice to support Miniflux out of the box.

Thank you.

**Comment by mrgodhani** [comment]
@tandy-1000 You can use Miniflux if you install Fever API extension https://miniflux.app/docs/services.html
