### ISSUE TITLE
Unable to update hackernews feed same as #524

### ISSUE THREAD

**Issue by danielwangksu** [hello-efficiency-inc/raven-reader#526]
I've having the same issue with latest version 1.0.38 and 1.0.39. The subscription cannot be updated I tried https://news.ycombinator.com/rss and https://lwn.net/headlines/newrss.

**Comment by mrgodhani** [comment]
@danielwangksu On refresh all feed click, it would only refresh articles if there are any articles to be added. In general cron job for the refreshing, the article is 5 mins. You can change that setting in Preference or by clicking `Ctrl/Cmd + ,`.

I just tested it and refreshing is working fine.
