### ISSUE TITLE
Application is displaying two tray icons on Linux

### ISSUE THREAD

**Issue by BlueManCZ** [hello-efficiency-inc/raven-reader#527]
The application is displaying two tray icons on Linux. This bug came in 1.0.39 and is still present in 1.0.45.

![Snímek z 2021-02-18 14-49-09](https://user-images.githubusercontent.com/17854950/108366282-7abd8180-71f8-11eb-959b-80ae1f48d711.png)

**Distribution**: Gentoo Linux - 5.4.92-gentoo
**Environment**: Gnome 3 - 3.36.8

libappindicator-12.10.0

**Comment by ArchieMeng** [comment]
Same here
Distribution: Arch Linux - 5.11.13-zen1-1-zen
Environment: Plasma 5.21.4
WM: KWin

**Comment by mrgodhani** [comment]
The tray is removed entirely in the latest version v1.0.50

**Comment by zero77** [comment]
@mrgodhani 
Is there any way to start in the background at login.
