### ISSUE TITLE
Add more view layout

### ISSUE THREAD

**Issue by wuhanhui** [hello-efficiency-inc/raven-reader#529]
Please add some new layout such as card layout or improve the list layout with pictures.
## Card layout
![image](https://user-images.githubusercontent.com/9048191/108700660-e463c580-7541-11eb-844d-5addfc4aeebc.png)
## list layout with images
![image](https://user-images.githubusercontent.com/9048191/108700693-f3e30e80-7541-11eb-9769-53e334395a49.png)

**Comment by mrgodhani** [comment]
@wuhanhui Actually work is in progress to do complete overhaul/rewrite using Tailwind css.

**Comment by wuhanhui** [comment]
Nice job. I am looking forward to your new version.

**Comment by mrgodhani** [comment]
Now article list has thumbnail/cover images in the latest version
