### ISSUE TITLE
Inoreader Sync

### ISSUE THREAD

**Issue by jrad232** [hello-efficiency-inc/raven-reader#530]
On current version on WIndows 10. I try to add Inoreader, I get directed to webpage to sign in and authorize, get redirected back to app, but nothing happens after that. No feeds are added.

**Comment by mrgodhani** [comment]
I have made a possible fix on inoreader on the latest version. Please give it a try.

**Comment by jrad232** [comment]
Thanks for the quick update! I just tried it again, but not luck authorizing inoreader.

**Comment by mrgodhani** [comment]
@jrad232 Do you mind pasting your log file by going to following path `%USERPROFILE%\AppData\Roaming\{app name}\logs\{process type}.log`

Please upload on renderer.log.

It might be something is erring out in your sync process.

**Comment by jrad232** [comment]
[renderer.log](https://github.com/hello-efficiency-inc/raven-reader/files/6038022/renderer.log)

**Comment by jrad232** [comment]
I've installed all the latest updates, but still no luck.

**Comment by aegidius77** [comment]
Hi,
Same problem here : 

> 
[renderer.log](https://github.com/hello-efficiency-inc/raven-reader/files/6092775/renderer.log)

> 
> On current version on WIndows 10. I try to add Inoreader, I get directed to webpage to sign in and authorize, get redirected back to app, but nothing happens after that. No feeds are added.

**Comment by mrgodhani** [comment]
Fixed the issue in latest version 1.0.48

**Comment by aegidius77** [comment]
Thanks,

Raven Reader is now correctly registered in Inoreader control panel website.

But still no sync...

After authorizing in webpage, it goes back to Raven Reader Preference panel and nothing happens.
Tried to restart, no feed appear.

[renderer.log](https://github.com/hello-efficiency-inc/raven-reader/files/6101998/renderer.log)

**Comment by jrad232** [comment]
Yes, I got the same behavior when trying the latest update.

**Comment by mrgodhani** [comment]
@jrad232  @aegidius77 Windows seems to working. Is Antivirus/firewall possibly blocking the app from making API calls so you might need to allow that.

![VirtualBox_WinDev2102Eval_10_03_2021_20_06_37](https://user-images.githubusercontent.com/1529009/110720267-4546fb00-81dc-11eb-809b-a6a487ba9015.png)

**Comment by jrad232** [comment]
It is working now. I had to restart the app a couple times but now feeds are showing up for me.

**Comment by aegidius77** [comment]
Hi,
It works. 👍 
Thanks
