### ISSUE TITLE
Ability to View Read Articles By Per Feed Basis

### ISSUE THREAD

**Issue by RuthlessRuler** [hello-efficiency-inc/raven-reader#536]
**Describe the bug**
Articles do not appear in the Feed once read. IDK if its expected or Bug, but if expected please do add a toggle to disable such feature.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Raven Reader
2. Click on any from any subscription
3. Article Vanishes from that subscription view
4. Article Only available at Recently Read & Under Category of the Subscription if Made.

**Expected behaviour**
Articles should be marked read but still should show up in particular feed/Subscription they belong to.

**Desktop (please complete the following information):**
 - OS: KDE Neon
 - Browser: Firefox 86
 - Version: 1.0.44

**Additional context**

**Comment by mrgodhani** [comment]
@RuthlessRuler  That was on purpose. Subscriptions would only show unread article items. You can still see/search articles from All Articles. This has been the pattern in all readers.

**Comment by g-berthiaume** [comment]
@mrgodhani In my experienced, most RSS readers will do what @RuthlessRuler is describing
They will list all the blog posts from a subscription, regardless of their reading status.

For example, The Old Reader will display all articles by default and has a "Show unread only" button.

![image](https://user-images.githubusercontent.com/19377511/109440456-5e8fc080-7a00-11eb-92c8-4160ab74e3e0.png)

Thanks for your work. 
Raven Reader is beautiful.

**Comment by mrgodhani** [comment]
Solved in https://github.com/hello-efficiency-inc/raven-reader/issues/538 and available in the latest version

**Comment by jantin1** [comment]
Hello! I don't understand how to make read items visible in the feed of particular subscription. Following #538  I have disabled (off) "Automatically add to recently read" and it didn't really change anything, read items still not present when clicking on the subscription's individual feed. Curiously, when I click on a Category feed I can see unread items from the category's feeds. Could you explain how to enable this? I love Raven Reader and I'm grateful for your work on it. This thing is really the one single thing that bugs me in the whole app.
