### ISSUE TITLE
[Feature Request] Configure the "mark as read" behavior.

### ISSUE THREAD

**Issue by g-berthiaume** [hello-efficiency-inc/raven-reader#538]
**Is your feature request related to a problem? Please describe.**

When clicking on an article to see its content, Raven Reader automatically assumes I have read it and delete it from my feed.
This makes it hard to browse subscriptions. 

I'd like to be able to manually decide if I have finished reading an article.

**Describe the solution you'd like**
Can you add a setting to disable the "Automatically add to Recently Read"?

Thanks

**Comment by mrgodhani** [comment]
Available in Preference in the latest version

**Comment by g-berthiaume** [comment]
Thank you. 
Looking forward to trying it.
