### ISSUE TITLE
Right click to select category

### ISSUE THREAD

**Issue by sekuryti** [hello-efficiency-inc/raven-reader#539]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually edit each feed to change or add a category

**Describe the solution you'd like**
Right-click to select category

**Describe alternatives you've considered**
Table of feeds and bulk edit

**Comment by mrgodhani** [comment]
Manage categories and Feeds are now available inside Preference modal or `Cmd+,` or in Windows `Ctrl+,` 
Released in 1.0.48
