### ISSUE TITLE
Remove article content from list view (only title and date visible)

### ISSUE THREAD

**Issue by ghost** [hello-efficiency-inc/raven-reader#541]
**Is your feature request related to a problem? Please describe.**
The list view is currently showing the start of articles. I rather just want it to be a clear overview of available articles.

**Describe the solution you'd like**
Have the article list be a proper article list, not a content previewer.

**Describe alternatives you've considered**
Inoreader provides this functionality, but I am looking for a non-web solution.

**Additional context**
Inoreader provides a good article list overview:
![inoreader](https://user-images.githubusercontent.com/15217150/110212268-e3fcf000-7e9a-11eb-9d02-813e7b61fdfd.png)

**Comment by mrgodhani** [comment]
Added new preference setting option to turn off content preview with images in the latest version.
