### ISSUE TITLE
Closing the application does not close it, it minimises it to the system tray

### ISSUE THREAD

**Issue by ghost** [hello-efficiency-inc/raven-reader#542]
**Describe the bug**
The close button does not close the application. It minimises it to the system tray.

**To Reproduce**
1. Press the close button.
2. Observe as it is not closed. It is still open but minimised in the system tray.

**Expected behavior**
For the software to close entirely.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v1.0.47

**Additional context**
Perhaps add an option that individuals can toggle "Minimise to the system tray when closing".

**Comment by mrgodhani** [comment]
Removed tray completely in the latest version.
