### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by aegidius77** [hello-efficiency-inc/raven-reader#543]
Hi,

Some evil automatic french translation :

- " feed " may be translated as " flux " and not as "aliment " which means " food " (in top left corner in main panel)
- " proxy " : why not just " proxy " instead of  " procuration ", like in the rest of the preferences panel
-  export/import could be " exporter des abonnements " and " importer des abonnements " instead of " abonnements à l'exportation/ à l'importation"

How to turn into full english language interface ? Would be helpfull to submit as good translations as possible (have a half english-french interface right now).

**Comment by A-d-r-i** [comment]
> have a half english-french interface right now

Absolutely, same issue for me.

Perhaps a collaborative translation solution could be considered (eg: [crowdin](https://crowdin.com), etc...)?

**Comment by mrgodhani** [comment]
@aegidius77 @A-d-r-i  Locales are in public folder PR is also helpful here to fix that

**Comment by aegidius77** [comment]
Thanks for the tip. Here are some suggestions :

fr- french

{
    "All Feeds": "Tous les flux",
    "Show more": "Montrer plus",
    "Show less": "Montrer moins",
    "Refresh All Feeds": "Rafraîchir tous les flux",
    "Delete all feed, category and article data": "Supprimer les données de flux, de catégorie et d'article",
    "Proxy Setting": "Paramètres du proxy",
    "Set proxy & restart": "Définir le proxy et redémarrer",
    "Connect Instapaper": "Se connecter à Instapaper",
    "Connect pocket": "Se connecter à Pocket",
    "Enter email": "Entrez votre courriel",
    "Read it later services": "Services de lecture différée",
    "Save articles to read it later services": "Sauvegarder les articles vers un service de lecture différée",
    "Mark as unfavourite": "Retirer des favoris",
    "View": "Affichage",
    "Item": "Élément" or "Article",
    "Next item": "Élément suivant" or "Article suivant",
    "Previous item": "Élément précédent" or "Article précédent",
    "Import subscriptions": "Importer des abonnements",
    "Export subscriptions": "Exporter des abonnements",
}

**Comment by mrgodhani** [comment]
@aegidius77  you can fork repo and create changes to do PR

**Comment by aegidius77** [comment]
Done !

**Comment by mrgodhani** [comment]
This is implemented in latest version
