### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by sekuryti** [hello-efficiency-inc/raven-reader#544]
I appreciate your effort, and development is good speed but you have to stop using deprecated packages that are not maintained - this is a security issue for everyone.

Example: https://www.npmjs.com/package/http2

**Comment by sekuryti** [comment]
# npm audit report

jquery  <3.5.0
Severity: moderate
Cross-Site Scripting - https://npmjs.com/advisories/1518
No fix available
node_modules/@postlight/mercury-parser/node_modules/jquery
  @postlight/mercury-parser  *
  Depends on vulnerable versions of jquery
  node_modules/@postlight/mercury-parser

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

**Comment by sekuryti** [comment]
I have forked and will see what I can fix.

**Comment by sekuryti** [comment]
# npm audit report

jquery  <3.5.0
Severity: moderate
Cross-Site Scripting - https://npmjs.com/advisories/1518
No fix available
node_modules/@postlight/mercury-parser/node_modules/jquery
  @postlight/mercury-parser  *
  Depends on vulnerable versions of jquery
  node_modules/@postlight/mercury-parser

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

**Comment by mrgodhani** [comment]
@sekuryti  Thanks. Just ran yarn audit following is the result.

```
➜  raven-reader git:(master) yarn audit
yarn audit v1.22.10
warning Resolution field "js-yaml@3.13.1" is incompatible with requested version "js-yaml@~3.1.0"
warning Resolution field "yargs-parser@13.1.2" is incompatible with requested version "yargs-parser@^4.2.0"
0 vulnerabilities found - Packages audited: 1924
✨  Done in 1.63s.
```

**Comment by sekuryti** [comment]
Yarn doesn't seem to catch many, I will post more info tomorrow but for now you can see npm auditl...

`~/Research/raven-reader(master*) » npm audit                                                                                           RSRCH@D92GROUP
# npm audit report

jquery  <3.5.0
Severity: moderate
Cross-Site Scripting - https://npmjs.com/advisories/1518
No fix available
node_modules/@postlight/mercury-parser/node_modules/jquery
  @postlight/mercury-parser  *
  Depends on vulnerable versions of jquery
  node_modules/@postlight/mercury-parser

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.`

**Comment by sekuryti** [comment]
This project needs a big overhaul for v2, you should replace libraries will well-maintained ones - I have forked this project and will attempt to modernise the dependencies.

**Comment by mrgodhani** [comment]
Closing this as packages were updated.
