### ISSUE TITLE
Fever sync not working

### ISSUE THREAD

**Issue by DJManas** [hello-efficiency-inc/raven-reader#547]
Hello,

I have TTRSS installed on RPi. In the TTRSS i am using fever plugin, to sync with fever enabled apps like Reeder. Recently I had moved from Mac OS to linux and found out that raven reeder seems the best alternative for Reeder so far, but when I insert the account, it is not syncing. Maybee it has something to do with "groups" in TTRSS, because when I pair the account I only see the group names, but no articles.
![image](https://user-images.githubusercontent.com/2048276/114779218-1fca8580-9d76-11eb-88cd-6d3e500c66ce.png)

**To Reproduce**
1. Setup TTRSS server
2. Install fever plugin into it
3. Open Raven Reader
4. Insert the account there
5. You should not see anythin synced

**Expected behavior**
Sync is working

**Screenshots**
Added in description

**Desktop (please complete the following information):**
 - OS: Gentoo 5.10.27-gentoo-dist #1 SMP Wed Mar 31 07:57:56 -00 2021 x86_64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz GenuineIntel GNU/Linux
 - Browser MS Edge dev Version 91.0.845.2 (Official build) dev (64-bit)
 - Version of Raven Reader 1.0.49

**Comment by mrgodhani** [comment]
@DJManas Thanks I will look into it and back with fix.

**Comment by DJManas** [comment]
@mrgodhani Great, thanks. If anything is needed, please let me know. And one more thing, I don't know if it has some consequences, but I am using .AppImage standalone version.

**Comment by mrgodhani** [comment]
Fixes made in v1.0.50

**Comment by DJManas** [comment]
Great, thanks.
