### ISSUE TITLE
Not full translate in file

### ISSUE THREAD

**Issue by vanja-san** [hello-efficiency-inc/raven-reader#553]
**Describe the bug**
Not full translate in file.

**To Reproduce**
- Blank

**Expected behavior**
Full translation text in file. Am use Russian language!

**Screenshots**
![изображение](https://user-images.githubusercontent.com/7201687/116875990-fbabe700-ac45-11eb-8fb4-068a136feeee.png)
-----
![изображение](https://user-images.githubusercontent.com/7201687/116876813-3febb700-ac47-11eb-99d9-8f13842c9bb8.png)
-----
![изображение](https://user-images.githubusercontent.com/7201687/116876875-5abe2b80-ac47-11eb-9132-5c8650114ef1.png)
-----
![изображение](https://user-images.githubusercontent.com/7201687/116876994-8c36f700-ac47-11eb-89bd-44effd49f5d7.png)
-----
![изображение](https://user-images.githubusercontent.com/7201687/116877074-a4a71180-ac47-11eb-8bb3-e7d7f4759061.png)
-----
![изображение](https://user-images.githubusercontent.com/7201687/116877176-caccb180-ac47-11eb-836e-c90eab59e2ea.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [88.0]

**Smartphone (please complete the following information):**
 - Blank

**Additional context**
Not all translation in file!

**Comment by mrgodhani** [comment]
Added more translation keys in latest version
