### ISSUE TITLE
Raven no longer opens!

### ISSUE THREAD

**Issue by A-d-r-i** [hello-efficiency-inc/raven-reader#555]
**Describe the bug**
Since version 1.0.50 the application no longer opens (as we can see on this gif :)
![RAVEN-BUG](https://user-images.githubusercontent.com/27277698/117117510-e8a52e00-ad8f-11eb-829a-f8f7548a2dae.gif)

**To Reproduce**
1. Go to 'C:\Users\user\AppData\Local\Programs\Raven Reader'
2. Click on 'Raven Reader.exe'
3. See error

**Desktop (please complete the following information):**
 - OS: Windows 10 pro x64
 - Version Raven Reader [from version 1.0.50 and now 1.0.51]

**Additional context**
The program nevertheless works well because I receive the update notifications from the rss feeds.

**Comment by mrgodhani** [comment]
@A-d-r-i  Thanks for reporting. Will investigate on this.

**Comment by mrgodhani** [comment]
@A-d-r-i  Hmm I tried on windows 10 seems to be working with v 1.0.51

<img width="1671" alt="Screen Shot 2021-05-06 at 10 16 45 PM" src="https://user-images.githubusercontent.com/1529009/117388525-eb4f7280-aeb8-11eb-91cd-eb03cd6e5a20.png">

**Comment by A-d-r-i** [comment]
Thanks @mrgodhani, it looks like I didn't uninstall properly when trying to fix the problem.

Thanks again, the problem is solved!
