### ISSUE TITLE
Bug: No feed found on infosec-handbook.eu

### ISSUE THREAD

**Issue by gregoryhammond** [hello-efficiency-inc/raven-reader#556]
**Describe the bug**
Trying to add https://infosec-handbook.eu/index.xml as a feed, but the app is saying that there is no feed found.

**To Reproduce**
1. Go to Add
2. Enter https://infosec-handbook.eu/index.xml into the blank box
3. See error

**Expected behavior**
Feed is valid and should be able to be added.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 1.0.51

**Additional context**
Go to the bottom of https://infosec-handbook.eu and there is a link to the rss feed.

**Comment by gregoryhammond** [comment]
Also found [https://www.cloudways.com/blog/updates/feed/](https://www.cloudways.com/blog/updates/feed/) has the same issue.

**Comment by mrgodhani** [comment]
> Also found [https://www.cloudways.com/blog/updates/feed/](https://www.cloudways.com/blog/updates/feed/) has the same issue.

This sounds like due to their security system blocking it when we try to fetch and parse

**Comment by mrgodhani** [comment]
@gregoryhammond https://infosec-handbook.eu/index.xml should be now working in 1.0.52.  working on figuring out other link.

**Comment by mrgodhani** [comment]
Cloudways is just blocking readers to parse due to their security system. Unfortunately, nothing we can do.
