### ISSUE TITLE
[Feature Request] Switch default reading view

### ISSUE THREAD

**Issue by DJManas** [hello-efficiency-inc/raven-reader#560]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Setting so I can make "View Default" as default view for feeds. It would be great on per feed basis, but global would be great also.

**Describe alternatives you've considered**
Problem is, that I have page with login and when I switch to Full Article by default view it doen't take my login cookie into account so I dont see full article.

**Additional context**
Full Article view asks me to login
![image](https://user-images.githubusercontent.com/2048276/118247481-86d97800-b4a3-11eb-8fbc-494b61ce9e23.png)

When I open Original view I see whole article, I found the article which the previos cuts now it seen it continues.
![image](https://user-images.githubusercontent.com/2048276/118247740-d3bd4e80-b4a3-11eb-9db6-c684e804091a.png)

Thanks,
Regards,
Petr Sourek

**Comment by mrgodhani** [comment]
Added in latest version

**Comment by DJManas** [comment]
Thank you, works great.
