### ISSUE TITLE
Wrong dates displayed in the list

### ISSUE THREAD

**Issue by DJManas** [hello-efficiency-inc/raven-reader#562]
**Describe the bug**
When I go into the list of articles, they are sorted correctly by date, but when I look at the dates of each item in the list, its the same and looks like its date and time of application launch. When I go to article it shows correct one, and as I had said, the list is properly sorted. Maybe the picture with highlights will be more clear than my description.

**To Reproduce**
1. Open Raven reader,
2. Go to list of articles
3. Look at date and times

**Expected behavior**
It should display date and time of the article, fetched. It should be somewhere there, but its not displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/2048276/118375991-9fda4a00-b5c5-11eb-846b-b141348eb6b2.png)

**Desktop (please complete the following information):**
 - OS: Gentoo Linux (5.10.27-gentoo-dist #1)
 - MS Edge, Preview 92.0.884.2, there had been update today, but it was even before update
 - Raven Reader 1.0.52

**Comment by mrgodhani** [comment]
Should be fixed in the latest version. Dates are dependent on the user's timezone.

**Comment by DJManas** [comment]
Downloaded new version (1.0.54) and now I dont see dates at all.
![image](https://user-images.githubusercontent.com/2048276/118391134-08134500-b633-11eb-8d48-4545e8df037a.png)

Thats good, that its in users timezone, but users timezone wont show 4 day's difference.

**Comment by mrgodhani** [comment]
Dates are shown in the humanized language now. But if you hover on `a few seconds ago`. You will see the timestamp

**Comment by DJManas** [comment]
@mrgodhani Yes, its good, but the timestamp behind it seems the date and time of last succesfull synchronization with server, or maybee its only Fever synchronization bug? Because I see **a few seconds ago** at every item in the list and if I go to list I have very old articles, like from March, you can see **a few seconds ago**, but the article is from march.
![image](https://user-images.githubusercontent.com/2048276/118613579-2c9c2800-b7bf-11eb-88fb-951dc0d67d2b.png)

I wanted to take a look into metadata, because it seems, that the articles are sorted properly, so the right timestamp must be there somewhere, but I did not find LDB browser.

Thanks,
Regards,
Petr Sourek

**Comment by mrgodhani** [comment]
@DJManas I see if you referring to sync then yes it does seem to be a bug. I will be fixing in new update.

**Comment by DJManas** [comment]
@mrgodhani Thanks. I am sorry, I had forgot to mention the Fever sync option, next time I will mention it, since I am using TTRSS to sync my RSS over devices. But no need to remember, next time I will mention it. Thanks.

**Comment by mrgodhani** [comment]
Fixed it in latest version v1.0.55

**Comment by DJManas** [comment]
Works, thanks.
