### ISSUE TITLE
Bug: Raven Reader displays all links as "visited" for Windows screen readers

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#563]
**Describe the bug**
I'm using Raven Reader with Windows screen readers for the visually impaired. The issue started a couple of weeks ago. Now screen readers think, and announce, that all links inside Raven Reader are "visited", meaning they have been accessed/opened before. So I hear the phrase, "visited link," upon encountering all links in Raven Reader. I'm using Raven Reader V1.0.54 at the moment.
**To Reproduce**
Simply navigate the app to reach links.

**Expected behavior**
Screen readers like NVDA should say, "link," upon reading linked articles.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by amirsol81** [comment]
@mrgodhani This is still reproduceable with V1.0.56. Could you please take a look? Hearing the phrase "visited link" for all links/articles/options -- including the apps main options such as "Visited link favourites", "Visited link recently read", etc. -- is really annoying.

**Comment by amirsol81** [comment]
@mrgodhani In addition, with V1.056 it's not possible to hide Raven Reader and send it to the Task Tray on Windows 10, meaning the "Hide Raven Reader Win" menu item and the Windows+H key stroke don't work at all.

**Comment by mrgodhani** [comment]
The link visited issue should be fixed now on the latest version. The Task tray feature was removed.

**Comment by amirsol81** [comment]
@mrgodhani With V1.0.57 of Raven Reader, most links are still reported as being "visited":
1. All feeds/Favorites/Unread articles/Recently played/Saved articles/Show less are all reported as visited.
2. Only the "Subscriptions sections work normally and aren't reported as visited. However, if you expand a category under the "Subscriptions" sections, all items belonging to it are reported as visited.
3. All articles belonging to RSS feeds are reported as "visited".
So the latest fix corrects a minor subsection of the issue.
Also may I ask why the Task Tray feature has been removed? Keeping the app open all the time isn't good under most cirtumstances.
Thanks.
