### ISSUE TITLE
Indent feeds inside categories in the sidebar

### ISSUE THREAD

**Issue by dflock** [hello-efficiency-inc/raven-reader#564]
The sidebar would be easier to scan if feeds were indented slightly inside their category folders, rather than all flush up against the left-hand side. This is what mine currently looks like:

![Screenshot_2021-05-19_14-25-10](https://user-images.githubusercontent.com/47756/118886605-0c976200-b8ae-11eb-8a24-42ecdcdf44d2.png)

Something like this would be better, I think:

![Screenshot_2021-05-19_14-25-10-indent](https://user-images.githubusercontent.com/47756/118887109-bb3ba280-b8ae-11eb-8b25-6e56c9b60eb4.png)

**Comment by mrgodhani** [comment]
Fixed in v1.0.55
