### ISSUE TITLE
Clicking on a feed in the sidebar does nothing

### ISSUE THREAD

**Issue by dflock** [hello-efficiency-inc/raven-reader#566]
**Describe the bug**
This worked fine the first time that I ran Raven, but hasn't worked since. I can use the sidebar normally - open & close categories and click on feeds - but this never affects the other panes - I can't see the feed items or view anything.
When Raven start up, it lists the most recent items (I think) in the middle pane. These are visible and hovering them gives you the hand cursor, but clicking them does nothing.

I have no idea if this is related to #565, which I see when starting from the command line.

**To Reproduce**
1. Start Raven
2. Try to click on a feed item
4. Note that nothing happens

**Expected behavior**
Well, it should display the selected feed's items, then allow you view an item by clicking on it.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04

**Additional context**

Installed Raven using the AppImage, currently running 1.0.54. Using this command to start Raven: `/home/duncan/Applications/Raven-Reader-1.0.54_3c36340c8f608f8705d1256ff8e52e28.AppImage --no-sandbox %U`

**Comment by dflock** [comment]
How can I help to debug this? Is there any way to get the Developer Tools/Console from within Raven?

**Comment by mrgodhani** [comment]
Feed FYI only shows unread items. If all items are read then it would be empty.

**Comment by dflock** [comment]
It's not that - sidebar in Raven shows counts of unread items next to these feeds, and they definitely have unread items, as verified by visiting their websites & other readers.

**Comment by mrgodhani** [comment]
> How can I help to debug this? Is there any way to get the Developer Tools/Console from within Raven?

You can debug and yes it does have console. For that you just have to clone this repo and follow steps of development. That is yarn install and yarn electron:serve to run jn dev mode in your machine. Obviously you would need node LTS in your system to make this happen.

**Comment by mrgodhani** [comment]
> It's not that - sidebar in Raven shows counts of unread items next to these feeds, and they definitely have unread items, as verified by visiting their websites & other readers.

Are you running or syncing any cloud based account?

**Comment by dflock** [comment]
> Are you running or syncing any cloud based account?

No, I'm not.

So, I closed Raven, found the `~/.config/Raven Reader` folder and renamed it, then started Raven again. This fixed it. I can give you a copy of the old folder, if that would be useful?

**Comment by mrgodhani** [comment]
> > Are you running or syncing any cloud based account?
> 
> 
> 
> No, I'm not.
> 
> 
> 
> So, I closed Raven, found the `~/.config/Raven Reader` folder and renamed it, then started Raven again. This fixed it. I can give you a copy of the old folder, if that would be useful?

Sure that would be helpful

**Comment by dflock** [comment]
[Raven Reader - backup.zip](https://github.com/hello-efficiency-inc/raven-reader/files/6523137/Raven.Reader.-.backup.zip)

**Comment by mrgodhani** [comment]
Should be fixed now in latest version v1.0.56
