### ISSUE TITLE
Add " Mark All as Unread" Option

### ISSUE THREAD

**Issue by mohitmeanslove** [hello-efficiency-inc/raven-reader#569]
There is no option like "Mark All As Unread " Available on this software.

**Comment by mrgodhani** [comment]
@mohitmeanslove whats the use case of marking it all as unread?

**Comment by mohitmeanslove** [comment]
Suppose a person get 100 new item feeds. He has marked all of them as read by mistake. Now he can't rectify his mistake.

**Comment by mohitmeanslove** [comment]
A request to you. Please download 'greader' app on your android based mobile and use it for 1-2 days. This small mobile app has more features than this desktop software. It will give you many new ideas which you can add in your software.

**Comment by mrgodhani** [comment]
Added this feature in latest version
