### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by DavidCarl** [hello-efficiency-inc/raven-reader#578]
Hello

We sent you guys a email a couple of weeks ago, and we would really like a response.

Would it be possible for you to take a look at your welcome email?

Sincerely
David Carl

**Comment by mrgodhani** [comment]
@DavidCarl whats the email address that we should be looking at? We dont see email under David Carl

**Comment by DavidCarl** [comment]
@mrgodhani it was sent to welcome@helloefficiency.com from daca@itu.dk

**Comment by mrgodhani** [comment]
The issue is resolved in the latest version.
