### ISSUE TITLE
problem with Raven-Reader-1.0.58.AppImage

### ISSUE THREAD

**Issue by z00rat** [hello-efficiency-inc/raven-reader#579]
**Describe the bug**
when i tried to update https://aur.archlinux.org/packages/raven-reader i was getting error 
we use AppImage version to create package for archlinux

so after some testing i found that,
if you run Raven-Reader-1.0.58.AppImage (new) while **~/.config/Raven\ Reader** exists from last version it will give you 
```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token . in JSON at position 0
    at JSON.parse (<anonymous>)
    at ElectronStore.Conf._deserialize (/tmp/.mount_Raven-IbhJJN/resources/app.asar/node_modules/conf/dist/source/index.js:69:43)
    at ElectronStore.get store [as store] (/tmp/.mount_Raven-IbhJJN/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
    at new Conf (/tmp/.mount_Raven-IbhJJN/resources/app.asar/node_modules/conf/dist/source/index.js:132:32)
    at new ElectronStore (/tmp/.mount_Raven-IbhJJN/resources/app.asar/node_modules/electron-store/index.js:69:3)
    at Module.<anonymous> (/tmp/.mount_Raven-IbhJJN/resources/app.asar/background.js:2:5134866)
    at r (/tmp/.mount_Raven-IbhJJN/resources/app.asar/background.js:2:110)
    at Object.<anonymous> (/tmp/.mount_Raven-IbhJJN/resources/app.asar/background.js:2:1968340)
    at r (/tmp/.mount_Raven-IbhJJN/resources/app.asar/background.js:2:110)
    at /tmp/.mount_Raven-IbhJJN/resources/app.asar/background.js:2:902
    at Object.<anonymous> (/tmp/.mount_Raven-IbhJJN/resources/app.asar/background.js:2:913)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
libva error: /usr/lib/dri/iHD_drv_video.so init failed
failed to open /usr/lib/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
```
 and stuck
 
if you delete the **~/.config/Raven\ Reader** and run new AppImage, it will work fine 
but after running new version once if you run previous version again, the previous version will work 
but the new version will give you same error again 

**To Reproduce**
1. download new Raven-Reader-1.0.58.AppImage
2. run previous Raven-Reader to generate ~/.config/Raven\ Reader
3. run new Raven-Reader-1.0.58.AppImage

**Expected behavior**
no error just this output ....
```
(electron) Security Warning: A WebContents was just created with both webviewTag and contextIsolation enabled.  This combination is fundamentally less secure and effectively bypasses the protections of contextIsolation.  We strongly recommend you move away from webviews to OOPIF or BrowserView in order for your app to be more secure
libva error: /usr/lib/dri/iHD_drv_video.so init failed
failed to open /usr/lib/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
09:19:50.593 › APPIMAGE env is not defined, current application is not an AppImage
(node:62795) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from
    at Ar.enable (/opt/raven-reader/resources/app.asar/background.js:2:5147942)
    at Object.enableBlockingInSession (/opt/raven-reader/resources/app.asar/background.js:2:5213155)
    at /opt/raven-reader/resources/app.asar/background.js:2:5213543
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `raven-reader --trace-warnings ...` to show where the warning was created)
(node:62795) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:62795) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/78788887/121794236-71817600-cc28-11eb-8afb-2bf4881afa68.png)

**Desktop (please complete the following information):**
 - OS: manjaro linux
 - Version `Linux manjaro-kun 5.10.41-1-MANJARO #1 SMP PREEMPT Fri May 28 19:10:32 UTC 2021 x86_64 GNU/Linux`
 

**Additional context**
should i wait for the bug to be fixed ?? or should i update the package ??

**Comment by ArchieMeng** [comment]
I am one of the maintainers of [AUR raven-reader](https://aur.archlinux.org/packages/raven-reader).
I tried the new version raven-reader on my machine, and it works fine.
And the info below is my machine info. I hope it may help excluding wrong cases.
> System:    Host: silver-ghost Kernel: 5.12.9-zen1-1-zen x86_64 bits: 64 Desktop: KDE Plasma 5.22.0 Distro: Arch Linux 
CPU:       Info: Quad Core model: Intel Core i5-1035G7 bits: 64 type: MT MCP cache: L2: 6 MiB 
           Speed: 1488 MHz min/max: 400/3700 MHz Core speeds (MHz): 1: 1488 2: 2018 3: 1962 4: 2352 5: 2349 6: 2414 7: 2701 
           8: 1973 
Graphics:  Device-1: Intel Iris Plus Graphics G7 driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel Iris Plus Graphics (ICL GT2) v: 4.6 Mesa 21.1.2

**Comment by z00rat** [comment]
@ArchieMeng dose it work fine with previous versions config files ??

**Comment by ArchieMeng** [comment]
> @ArchieMeng dose it work fine with previous versions config files ??

What do you mean previous config files? I just updated raven-reader from 1.0.57 to 1.0.58

**Comment by z00rat** [comment]
> What do you mean previous config files? I just updated raven-reader from 1.0.57 to 1.0.58
yeah its weird ...
your cant create the same error 

im gonna try to build in an arch vm later 
lets see whats happens then

**Comment by z00rat** [comment]
arch vm giving me same error 
looks like its not manjaro's problem .....

![image](https://user-images.githubusercontent.com/78788887/121802656-4108fe80-cc5f-11eb-8266-937e675e83d7.png)

**Comment by z00rat** [comment]
looks what i have found 

v57's config is corrupted / broken for i dont what reason 
and now new v58 trying to read it and gave me this error 

![image](https://user-images.githubusercontent.com/78788887/121802794-22efce00-cc60-11eb-91a7-18aa61fe7b3b.png)

im gonna try v56 and other's to so see why v57 never gave any error when we ran it for the first time .....

**Comment by z00rat** [comment]
i just tried v1.0.55, v1.0.56, v1.0.57 and v1.0.58

looks like dev roll out a config breaking release 
other than v58, other can use any other's config file without any problem

![image](https://user-images.githubusercontent.com/78788887/121803553-05bcfe80-cc64-11eb-8b44-3e2980126695.png)

now i will wait for dev to make this backward compatible or tell us what we should do.

**Comment by ArchieMeng** [comment]
> i just tried v1.0.55, v1.0.56, v1.0.57 and v1.0.58
> 
> looks like dev roll out a config breaking release
> other than v58, other can use any other's config file without any problem
> 
> ![image](https://user-images.githubusercontent.com/78788887/121803553-05bcfe80-cc64-11eb-8b44-3e2980126695.png)
> 
> now i will wait for dev to make this backward compatible or tell us what we should do.

According to this comment, I checked my $HOME/.config/Raven\ Reader/config.json as well. It is also corrupted, but somehow it works on my machine.

**Comment by mrgodhani** [comment]
config created is not corrupted but now encryption is added to it

**Comment by z00rat** [comment]
> config created is not corrupted but now encryption is added to it

then what now ??
v1.0.58 is giving me error and not @ArchieMeng 

its a big problem 
as we make a package we can't change $HOME directory's files 
and as the problem dont create any window, people will get confused.

so it will be better if guys can roll out a new version with backward compatibility with previous config file
or some kinda error with a window from the app

if you guys dont wanna do that we will update with a massage to delete ~/.config/Raven\ Reader/config.json
and hope people will notice it 

its up to you guys 
now what we should do ??

**Comment by z00rat** [comment]
> And I performed a fresh install of raven-reader. The fresh config.json created by 1.0.58 is corrupted.

why the hell your's one making encrypted one but mine ??
even in archlinux vm

![image](https://user-images.githubusercontent.com/78788887/121816873-ef349880-cc9f-11eb-9249-639c2f6390b6.png)

ok @ArchieMeng 
can you run this command to check our dependency versions 
`pacman -Qi libxss libxtst libappindicator-gtk2 gconf-gtk2 libnotify | grep "Version"`
my ones output is 
```
Version         : 1.2.3-3
Version         : 1.2.3-4
Version         : 12.10.0.r296-1
Version         : 3.2.6-5
Version         : 0.7.9-1
```

**Comment by z00rat** [comment]
new v1.0.59 is not backward compatible with v1.0.57's config
and now v57 breaks with v59's config as the same was 

![image](https://user-images.githubusercontent.com/78788887/121831955-a7872e80-ccea-11eb-8842-0a9f0a8e5949.png)

**Comment by mrgodhani** [comment]
@z00rat you can just delete the config and regenerate the file. Config file only stores setting preferences. Nothing else.

**Comment by z00rat** [comment]
> @z00rat you can just delete the config and regenerate the file by opening app or reinstalling. Config file only stores setting preferences. Nothing else.

thats what im doing
but as this error dont create a window or something like that to notify user 
we cant update the package in the arch user repository

**Comment by mrgodhani** [comment]
Complete uninstall and reinstall should fix your issue. Unfortunately I am not aware of all linux system on how they function.

**Comment by z00rat** [comment]
> Complete uninstall and reinstall should fix your issue. Unfortunately I am not aware of all linux system on how they function.

sorry we that will not happen 
because that config file is inside $HOME directory 
and that package we build cant touch anything in there for security and privacy reasons 

as for uninstall that config will not be removed 
again because we cant touch anything in $HOME
user have manually remove that config file 
or the app have to do it  

now,
can you code to check for that error and gave user a error window ??
or
delete and regenerate if it cant read ??

it will be better for user because many may not read the _"post install massage"_  we can send

**Comment by ArchieMeng** [comment]
>ok @ArchieMeng
can you run this command to check our dependency versions
pacman -Qi libxss libxtst libappindicator-gtk2 gconf-gtk2 libnotify | grep "Version"

Ok, @z00rat. My output is the same as yours.
![image](https://user-images.githubusercontent.com/12139431/121839075-d8c42680-cd0b-11eb-8b0b-18b1e6b02198.png)

> Complete uninstall and reinstall should fix your issue. Unfortunately I am not aware of all linux system on how they function.

My first question is why preference should be encrypted. And another thing is what is the encryption difference between 1.0.57 and the version after which may cause this update problem. 
Deleting config file is easy, __but it will make users losing their existing configs and unable to recover due to the encryption__. (Or, provide the method to decrypt the config is another alternative solution)

**Comment by mrgodhani** [comment]
> >ok @ArchieMeng
> 
> can you run this command to check our dependency versions
> 
> pacman -Qi libxss libxtst libappindicator-gtk2 gconf-gtk2 libnotify | grep "Version"
> 
> 
> 
> Ok, @z00rat. My output is the same as yours.
> 
> ![image](https://user-images.githubusercontent.com/12139431/121839075-d8c42680-cd0b-11eb-8b0b-18b1e6b02198.png)
> 
> 
> 
> > Complete uninstall and reinstall should fix your issue. Unfortunately I am not aware of all linux system on how they function.
> 
> 
> 
> My first question is why preference should be encrypted. And another thing is what the encryption difference between 1.0.57 and the version after is. This may explain what causes this update problem. 
> 
> Deleting config file is easy, __but it will make users losing their existing configs and unable to recover due to the encryption__. (Or, provide the method to decrypt the config is another alternative solution)

Its encrypted because it also includes password for sync accounts.

**Comment by ArchieMeng** [comment]
> Its encrypted because it also includes password for sync accounts.

So, do changes in encryption break the software?

**Comment by mrgodhani** [comment]
> > Its encrypted because it also includes password for sync accounts.
> 
> So, do changes in 1.0.58 break the software?

issue seems only in Linux. But this has not been an issue in other operating systems like mac or Windows. So sorry my knowledge on Linux is low on how people install it. There are no new changes on 1.0.58 that breaks specific in linux. I will test out myself on Linux if anyone gives steps to reproduce. Thanks

**Comment by BlueManCZ** [comment]
I have the same problem here on Gentoo linux. I also cannot easily package this update. There should be at least some simple popup window saying: "Your config files are outdated. Please remove them and restart the application." Because there may be people with zero debugging skills and they can easily get confused, when the application is not starting correctly.

**Comment by ArchieMeng** [comment]
After I update raven-reader to 1.0.59, it crashes as well.

```bash
 A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token π in JSON at position 0
    at JSON.parse (<anonymous>)
    at ElectronStore.Conf._deserialize (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:69:43)
    at ElectronStore.get store [as store] (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
    at new Conf (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:132:32)
    at new ElectronStore (/opt/raven-reader/resources/app.asar/node_modules/electron-store/index.js:69:3)
    at Module.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:5127581)
    at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
    at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:1963683)
    at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
    at /opt/raven-reader/resources/app.asar/background.js:2:902
    at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:913)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
```

**Comment by mrgodhani** [comment]
Latest version should fix unexpected token issue.

**Comment by z00rat** [comment]
yeah it works fine now.
@ArchieMeng i updated the package in aur.

**Comment by ArchieMeng** [comment]
> yeah it works fine now.
> @ArchieMeng i updated the package in aur.

But it crashes on my side now.... No idea why. 

(upgrade from 1.0.57 to 1.0.60)
```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at ElectronStore.Conf._deserialize (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:69:43)
    at ElectronStore.get store [as store] (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
    at new Conf (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:132:32)
    at new ElectronStore (/opt/raven-reader/resources/app.asar/node_modules/electron-store/index.js:69:3)
    at Module.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:5127581)
    at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
    at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:1963683)
    at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
    at /opt/raven-reader/resources/app.asar/background.js:2:902
    at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:913)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
```

(upgrade from 1.0.58 to 1.0.60)
```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at ElectronStore.Conf._deserialize (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:69:43)
    at ElectronStore.get store [as store] (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
    at new Conf (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:132:32)
    at new ElectronStore (/opt/raven-reader/resources/app.asar/node_modules/electron-store/index.js:69:3)
    at Module.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:5127581)
    at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
    at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:1963683)
    at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
    at /opt/raven-reader/resources/app.asar/background.js:2:902
    at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:913)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
```

**Comment by z00rat** [comment]
> > yeah it works fine now.
> > @ArchieMeng i updated the package in aur.
> 
> But it crashes on my side now.... No idea why.
> 1.0.57 and 1.0.58 are working on my side while 1.0.59 and 1.0.60 are not.
> 
> (upgrade from 1.0.57 to 1.0.60)
> 
> ```
> A JavaScript error occurred in the main process
> Uncaught Exception:
> SyntaxError: Unexpected token  in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at ElectronStore.Conf._deserialize (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:69:43)
>     at ElectronStore.get store [as store] (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
>     at new Conf (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:132:32)
>     at new ElectronStore (/opt/raven-reader/resources/app.asar/node_modules/electron-store/index.js:69:3)
>     at Module.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:5127581)
>     at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
>     at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:1963683)
>     at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
>     at /opt/raven-reader/resources/app.asar/background.js:2:902
>     at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:913)
>     at Module._compile (internal/modules/cjs/loader.js:1078:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
>     at Module.load (internal/modules/cjs/loader.js:935:32)
>     at Module._load (internal/modules/cjs/loader.js:776:14)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
> ```
> 
> (upgrade from 1.0.58 to 1.0.60)
> 
> ```
> A JavaScript error occurred in the main process
> Uncaught Exception:
> SyntaxError: Unexpected token � in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at ElectronStore.Conf._deserialize (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:69:43)
>     at ElectronStore.get store [as store] (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
>     at new Conf (/opt/raven-reader/resources/app.asar/node_modules/conf/dist/source/index.js:132:32)
>     at new ElectronStore (/opt/raven-reader/resources/app.asar/node_modules/electron-store/index.js:69:3)
>     at Module.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:5127581)
>     at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
>     at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:1963683)
>     at r (/opt/raven-reader/resources/app.asar/background.js:2:110)
>     at /opt/raven-reader/resources/app.asar/background.js:2:902
>     at Object.<anonymous> (/opt/raven-reader/resources/app.asar/background.js:2:913)
>     at Module._compile (internal/modules/cjs/loader.js:1078:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
>     at Module.load (internal/modules/cjs/loader.js:935:32)
>     at Module._load (internal/modules/cjs/loader.js:776:14)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
> ```

the hell ??
v57 to v60 with no problem 
and i didnt check with v58 because we didnt update to that version in the first place

**Comment by ArchieMeng** [comment]
> the hell ??
> v57 to v60 with no problem
> and i didnt check with v58 because we didnt update to that version in the first place

It's exactly the same result: Crash.
