### ISSUE TITLE
Distrowatch feed not working

### ISSUE THREAD

**Issue by BenoitPoulet** [hello-efficiency-inc/raven-reader#584]
**Describe the bug**
No feed found for https://distrowatch.com/news/dw.xml

**To Reproduce**
1. Launch Raven
2. Click on 'add'
3. Paste "https://distrowatch.com/news/dw.xml"
4. "No feed found" is shown

**Expected behavior**
I expect the feed to be found; it's working with other apps.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11
 - Raven version : 1.0.57

**Comment by mrgodhani** [comment]
We use rss-parser to parse the RSS xml. Currently RDF type is not supported with rss-parser and hence reason it is not parsing. https://github.com/rbren/rss-parser/issues/107

**Comment by mrgodhani** [comment]
Fixed in latest version
