### ISSUE TITLE
Add "Open Original " As Default Open Action When Click Artical List

### ISSUE THREAD

**Issue by zqbxx** [hello-efficiency-inc/raven-reader#586]

**Comment by mrgodhani** [comment]
@zqbxx More elaboration. Open original as in full article?

**Comment by zqbxx** [comment]
> 
> 
> @zqbxx More elaboration. Open original as in full article?
**By default, raven-reader has two default action to open an article.**
![1](https://user-images.githubusercontent.com/3808964/124051825-cc500580-da4f-11eb-8bf7-e209236137be.jpg)

![3](https://user-images.githubusercontent.com/3808964/124051199-9e1df600-da4e-11eb-8266-5a07e9a028af.jpg)

**But I want to open article like this, as default open action**
![2](https://user-images.githubusercontent.com/3808964/124051186-99594200-da4e-11eb-8128-a41a80f2de18.jpg)

**Because, some site display abnormal, include some english site**
![4](https://user-images.githubusercontent.com/3808964/124051214-a24a1380-da4e-11eb-8cf2-d3f453130ab2.jpg)

**I can not find an option to open orgin page by default**
![5](https://user-images.githubusercontent.com/3808964/124051842-d40faa00-da4f-11eb-9044-b797ea07ec32.jpg)

**Comment by mrgodhani** [comment]
Fixed in latest version
