### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by bakinazik** [hello-efficiency-inc/raven-reader#588]
**Describe the bug**
when we say show full content, turkish characters doesn't appear..

**Expected behavior**
want to turkish characters appear

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/61169988/126362431-93a1ff53-93ac-4c7f-88c9-fc78ec2a076a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: im using windows app

**Comment by mrgodhani** [comment]
@bakinazik I can have the feed url?

**Comment by bakinazik** [comment]
https://www.gercekbilim.com/feed/

**Comment by mrgodhani** [comment]
@bakinazik This is an issue from parser Raven uses that is https://github.com/postlight/mercury-parser. It is not having certain characters correct.

**Comment by mrgodhani** [comment]
Closing this issue since problem is from the parser
