### ISSUE TITLE
Cant create feed after delete

### ISSUE THREAD

**Issue by SubaruSama** [hello-efficiency-inc/raven-reader#613]
**Describe the bug**
When you add a feed and delete the same feed, you cant add the same feed. It returns 'No feed found'

**To Reproduce**
1. Go to + Add
2. Enter the URL feed
3. Add the feed
4. Delete the previous feed
5. Go to + Add
6. Enter the URL feed
7. It returns 'No feed found'

**Expected behavior**
It should be capable of add and delete the same feed over and over.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: from the snapd

**Comment by mrgodhani** [comment]
@SubaruSama you want to provide feed link?

**Comment by SubaruSama** [comment]
Yeah, sorry.

The link is: https://raidforums.com/syndication.php?fid=202&limit=50

I didn't test  with other links. I can test with other rss feeds.

**Comment by mrgodhani** [comment]
This should be fixed in latest version
