### ISSUE TITLE
Feed fetching issue

### ISSUE THREAD

**Issue by equation-group** [hello-efficiency-inc/raven-reader#618]
**Describe the bug**
It is only fetching one article, while the feed has many articles.

**To Reproduce**
https://justinmeiners.github.io/feed.xml - add this feed

**Expected behavior**
it will only fetch 1 article

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10 latest

**Comment by mrgodhani** [comment]
@equation-group should be fixed in latest version
