### ISSUE TITLE
Can't subscribe to feeds

### ISSUE THREAD

**Issue by nibble-4bits** [hello-efficiency-inc/raven-reader#619]
**Describe the bug**
I'm trying to subscribe to monkeyuser.com [feed](https://www.monkeyuser.com/feed.xml), but the app responds with: "No feed found"

**To Reproduce**
1. Go to 'Subscriptions' in the app toolbar
2. Click on 'Add subscription'
3. Enter the following URL: https://www.monkeyuser.com/feed.xml
4. Press `Enter`
5. See _No feed found_ error

**Expected behavior**
Raven Reader should subscribe to the MonkeyUser feed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 1.0.65

**Additional context**
I'm also trying to subscribe to:

* [The New Oil](https://blog.thenewoil.org/). See [feed](https://write.as/thenewoil/feed/)
* And [Two Bit History](https://twobithistory.org/). See [feed](https://twobithistory.org/feed.xml)

But they don't work either

**Comment by mrgodhani** [comment]
Hmm Sounds like Windows centric issue. I am able to subscribe it in Mac.

**Comment by mrgodhani** [comment]
@nibble-4bits New version released please try again if it works.

**Comment by nibble-4bits** [comment]
@mrgodhani Yes, updating to the 1.0.68 version fixed the issue. Thanks!
