### ISSUE TITLE
No feeds found, after adding URL of RSS feed

### ISSUE THREAD

**Issue by SUCHITRAGIRI** [hello-efficiency-inc/raven-reader#626]
**Describe the bug**
I am using web version of Raven, here I am trying to add url for rss feed or want to subscribe but can't do it!
All the time it is showing "no feeds found".

**To Reproduce**
1. Go to '+'
2.  add my url of rss feed
3. Click on '+'
4. but showing this.. "no feed found"

**Expected behavior**
Actually I tried the same with another rss reader, it went well with "feedly" but don't know why its not working with "raven":(

**Screenshots**

![Screenshot (560)](https://user-images.githubusercontent.com/60110218/149498699-44c60510-1423-43b0-9caf-133ed255d877.png)

**Additional context**
Please help me out!!

**Comment by mrgodhani** [comment]
@SUCHITRAGIRI What's the url you are trying?

**Comment by SUCHITRAGIRI** [comment]
This one!
 https://dev.to/feed/suchitra_13

**Comment by mrgodhani** [comment]
@SUCHITRAGIRI thanks for reporting. Fixed now

**Comment by SUCHITRAGIRI** [comment]
Yup!
It's working now:)
