### ISSUE TITLE
macOS - Add Apple Silicon (M1)/Universal Binary

### ISSUE THREAD

**Issue by izaxone** [hello-efficiency-inc/raven-reader#657]
Currently the macOS build of Raven Reader is compiled as an Intel binary. Though this works fine for Rosetta 2, running the Intel binary on Apple Silicon (M1) processors is less efficient, which may result in reduced battery life.

I would like to see either a separate Apple Silicon binary available, or a Universal Binary that supports both Intel and Apple Silicon. 

Article about compiling a Universal Binary on macOS via Xcode: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

An article about compiling for Apple Silicon with Electron: https://www.electronjs.org/blog/apple-silicon

**Comment by mrgodhani** [comment]
Added support for M1 in latest https://github.com/hello-efficiency-inc/raven-reader/releases/tag/v1.0.73
