### ISSUE TITLE
Expired/Invalid SSL Certificate?

### ISSUE THREAD

**Issue by Starscade** [hello-efficiency-inc/raven-reader#667]
Sorry, I know this isn't a bug. Just thought this would be more appropriate than emailing welcome@helloefficiency.com:
- Cloudflare reports a **526 Error** when attempting to visit https://web.ravenreader.app/
- Navigating to HTTP (no "S") also redirects to this error.

**Comment by mrgodhani** [comment]
@Starscade we shut down the web version. We found out that it is actually more costly for us to maintain in terms of servers etc vs receiving paid users against it.

**Comment by Starscade** [comment]
> @Starscade we shut down the web version. We found out that it is actually more costly for us to maintain in terms of servers etc vs receiving paid users against it.

😟 Understood. Just to follow up then--and perhaps you already know this, too--there's still a link to the web version at the bottom of the home page.

**Comment by mrgodhani** [comment]
Now that's the bug I will fix that thanks for letting know
