### ISSUE TITLE
Video player toggle fullscreen did not working as expected

### ISSUE THREAD

**Issue by lakuapik** [hello-efficiency-inc/raven-reader#671]
**Describe the bug**
Toggle fullscreen on the video player did not working as expected.

**To Reproduce**
1. Subscribe to youtube rss feed, eg: `https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA`
2. Click on one of the feed
3. Play the video
4. Click the fullscreen button

**Expected behavior**
The video player should be in fullscreen.

**Desktop (please complete the following information):**
* OS: kali-rolling 2022.2
* Browser: Chrome
* Version: Raven Reader 1.0.72

**Screenshots**
![image](https://user-images.githubusercontent.com/20186786/170872109-19c77079-2939-4a3c-a95b-1e985054aade.png)

**Comment by mrgodhani** [comment]
@lakuapik I didn't find any issues when trying in MacOS. This might be linux specific issue for your OS

**Comment by lakuapik** [comment]
@mrgodhani i will try to debug it locally, maybe it is linux specific or my distro specific.
