### ISSUE TITLE
Raven Reader not refreshing

### ISSUE THREAD

**Issue by Grimnir666** [hello-efficiency-inc/raven-reader#715]
**Describe the bug**
Since today, Raven Reader doesn't refresh any feeds anymore, yesterday it was working. It is also not possible to add new feeds. I get the message "No feed found".

I tested the feeds in another reader and there they are working.
Example feeds:
https://www.heise.de/rss/heise-Rubrik-IT-atom.xml
https://www.golem.de/rss

I'm running Raven Reader 1.0.77 via Snap on Linux Mint 19.03 Cinnamon but I also tested the AppImage, same behavior.

**Comment by mrgodhani** [comment]
Fixed in the latest build
