### ISSUE TITLE
Add RSS Bandit Features

### ISSUE THREAD

**Issue by Bydia** [hello-efficiency-inc/raven-reader#73]
Would like to see some of the basic features of RSS Bandit added. Like
1. grouping feeds
2. **set marked as read** by selecting items, feeds or group of feeds.
You can reference: http://rssbandit.org
Some icons need tooltips like the black circle. I have no idea what would happen if I clicked it.
For the Unread Articles, do not remove the selected item until I select a new item.

**Comment by mrgodhani** [comment]
Grouping of feeds to category is now included in latest version. Rest there are many other features included. Closing this.
