### ISSUE TITLE
RSS Can't be Found

### ISSUE THREAD

**Issue by o-data** [hello-efficiency-inc/raven-reader#732]
**Describe the bug**
Can't add RSS Feed.

**To Reproduce**
1. Add Feed: https://www.ghacks.net/
2. Fail, no feed found
3. Add Feed (on their website at bottom is their feed URL) https://www.ghacks.net/feed
4. Fail still.
5. Try a validator maybe that the issue: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.ghacks.net%2Ffeed%2F
6. This seem work fine... but Github is a Atom feed: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgithub.com%2Fhello-efficiency-inc%2Fraven-reader%2Freleases

**Expected behavior**
Raven Reader should be able to read RSS feed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows - Using Raven Read Portable
 - Browser Firefox
 - Version 102

**Additional context**
If need more info let me know

**Comment by mrgodhani** [comment]
@o-data This is because ghacks is blocking it from their end since they are using Cloudflare and it is asking the user to solve Recaptcha.
