### ISSUE TITLE
Support feeds requiring authentication

### ISSUE THREAD

**Issue by mshish** [hello-efficiency-inc/raven-reader#84]
**Is your feature request related to a problem? Please describe.**
I'd like to use rss-reader on some RSS feeds protected by Basic and NTLM auth. 

**Describe the solution you'd like**
Ideally, when I add a URL, it would let me either specify user and password for Basic Auth, toggle NTLM pass-through from Chromium, or even better load the feed in a hosted window and let me login to the feed using the URL and cache the cookies/auth tokens.

In Chrome, my browser just passes the NTLM auth from Windows, not sure if this is possible with Electron. I would be interested in trying to contribute this change if I could be pointed in the right direction in the code base.

**Comment by mrgodhani** [comment]
Idea isn't bad. I was wondering if you tried adding RSS feed that needs authentication in https://github.com/GetStream/Winds ? 

Otherwise I will look into this. Mostly it would go in https://github.com/mrgodhani/rss-reader/blob/master/src/renderer/components/SubscribeModal.vue

**Comment by mshish** [comment]
@mrgodhani thanks, I'm trying to avoid using a non-hosted service so have avoided Winds.

**Comment by mrgodhani** [comment]
The latest version now supports self-hosted services that support Google Reader API example: FreshRss.org
